In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
tabn = '303.40'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [4]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,digest_table_sub_title_note,has_SE,location_in,year_in,year,location,location_type,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,303.40,2019,A,,,FALSE,Title,Column,,United States,Region,Total fall enrollment in degree-granting posts...,[In thousands],"Attendance status, sex, and age",Distributions by age are estimates based on sa...,"U.S. Department of Education, National Center ...",This table was prepared April 2020.

In [5]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,is_standard_error,is_dollar,format_string,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,303.40,2019,A,,A,FALSE,,,1970,,,1970,,,,,,,,,,,,,
1,303.40,2019,A,,B,FALSE,,,1980,,,1980,,,,,,,,,,,,,
2,303.40,2019,A,,C,FALSE,,,1990,,,1990,,,,,,,,,,,,,
3,303.40,2019,A,,D,FALSE,,,2000,,,2000,,,,,,,,,,,,,
4,303.40,2019,A,,E,FALSE,,,2005,,,2005,,,,,,,,,,,,,
5,303.40,2019,A,,F,FALSE,,,2009,,,2009,,,,,,,,,,,,,
6,303.40,2019,A,,G,FALSE,,,2010,,,2010,,,,,,,,,,,,,
7,303.40,2019,A,,H,FALSE,,,2011,,,2011,,,,,,,,,,,,,
8,303.40,2019,A,,I,FALSE,,,2012,,,2012,,,,,,,,,,,,,
9,303.40,2019,A,,J,FALSE,,,2013,,,2013,,,,,,,,,,,,,
10,303.40,2019,A,,K,FALSE,,,2014,,,2014,,,,,,,,,,,,,
11,303.40,2019,A,,L,FALSE,,,2015,,,2015,,,,,,,,,,,,,
12,303.40,2019,A,,M,FALSE,,,2016,,,2016,,,,,,,,,,,,,
13,303.40,2019,A,,N,FALSE,,,2017,,,2017,,,,,,,,,,,,,
14,303.40,2019,A,,O,FALSE,,,2018,,,2018,,,,,,,,,,,,,
15,303.40,2019,A,,P,FALSE,,,2019,,,Projected,2019,,,,,,,,,,,,
16,303.40,2019,A,,Q,FALSE,,,2020,,,Projected,2020,,,,,,,,,,,,
17,303.40,2019,A,,R,FALSE,,,2021,,,Projected,2021,,,,,,,,,,,,
18,303.40,2019,A,,S,FALSE,,,2029,,,Projected,2029,,,,,,,,,,,,

In [6]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S
5,303.40,2019,A,,1,All students,,,,,,,,,,,,,,TRUE,,,,8580.886999999999,12096.894999999999,13818.636999999999,15312.289,17487.475,20313.593999999997,21019.438000000002,21010.59,20644.478000000003,20376.677,20209.092,19988.203999999994,19846.904,19778.151,19645.917999999998,19720.121,19744.128,19778.293,20114.735
6,303.40,2019,A,,2,All students,,14 to 17 years old,,,,,,,,,,,,FALSE,,,,262.72891638288763,256.80170753204686,152.87542424322658,131.3304768929476,187.27090299414286,215.4230037027092,202.21173319114206,220.68154806216683,242.00833948489424,256.1279998555416,238.54147657813442,213.6648965352224,213.82670069469827,210.0689349405242,206.23595802921676,204.081,205.423,207.037,204.088
7,303.40,2019,A,,3,All students,,18 and 19 years old,,,,,,,,,,,,FALSE,,,,2579.277939934982,2852.1965948935576,2776.6920474596905,3257.8824876308217,3443.7836881362828,4009.2415779540543,4056.89150430518,3955.816041853095,3781.5630471498835,3720.3484175194753,3720.047144295677,3732.2870114596208,3738.099183899561,3782.2979665240114,3768.463591450188,4090.562,4028.797,3996.324,4025.209
8,303.40,2019,A,,4,All students,,20 and 21 years old,,,,,,,,,,,,FALSE,,,,1884.9688144008035,2395.291906585815,2592.774558353114,3004.7101753229226,3562.731684553347,3915.5375536333613,4102.564657583997,4269.000095311492,4235.205845640079,4182.69364205898,4162.600987898017,4148.069763190261,4203.517106942427,4159.529718855144,4141.589833719785,4466.645,4518.83,4536.63,4517.249
9,303.40,2019,A,,5,All students,,22 to 24 years old,,,,,,,,,,,,FALSE,,,,1468.6403019870486,1946.520446966997,2201.9312780661257,2599.5322435059725,3114.1867920004433,3570.840902299781,3758.837732271317,3792.80806060723,3950.530838996498,3963.7470376917436,3910.41951607037,3784.775865469987,3736.2253827126224,3690.789410914398,3666.435318659822,3550.839,3539.93,3546.722,3619.312
10,303.40,2019,A,,6,All students,,25 to 29 years old,,,,,,,,,,,,FALSE,,,,1091.1832256559214,1842.5735923454063,2082.8122161122315,2044.334962089141,2469.3881939814155,3082.163154210431,3253.722519959335,3271.595314616563,3154.8198111106185,3050.47010387272,3084.2549711114316,3165.175668384839,3192.2860181231526,3225.551207258869,3194.053269045829,3057.613,3033.428,2996.118,2957.069
11,303.40,2019,A,,7,All students,,30 to 34 years old,,,,,,,,,,,,FALSE,,,,527.435609272238,1226.5837986098545,1384.1407212900726,1332.9125517998023,1438.1092179085174,1735.4155047333563,1804.872997286788,1788.2916399734881,1683.7804198158367,1605.9548155311654,1586.2878973145791,1600.149144642024,1588.876425875506,1586.8775679530258,1561.6796610332958,1565.363,1596.739,1631.949,1625.392
12,303.40,2019,A,,8,All students,,35 years old and over,,,,,,,,,,,,FALSE,,,,766.6521923661185,1576.9269530663223,2627.410754475538,2941.586102758394,3272.00452042585,3784.9723034663057,3840.336855402241,3712.397299575965,3596.5696978021915,3597.334983470374,3506.94000673179,3344.081650318044,3174.0731817520327,3123.0361935540272,3107.460368061862,2785.018,2820.981,2863.513,3166.416
13,303.40,2019,A,,9,All students,,Males,,,,,,,,,,,,TRUE,,,,5043.642,5874.373999999999,6283.909,6721.769000000001,7455.925,8732.953,9045.759000000002,9034.256000000001,8919.006000000001,8861.197,8797.529999999999,8723.819,8638.422,8571.313999999998,8442.662,8470.356,8475.922,8486.555,8629.844
14,303.40,2019,A,,10,All students,,Males,,14 to 17 years old,,,,,,,,,,FALSE,,,,125.36711447079658,106.12091439753542,65.86738163439115,58.320816023703436,68.16605584859434,102.65067460296618,93.90917409376875,104.41605998544495,119.06151281424114,125.48172280842513,117.4212985802469,94.05993093707835,82.56229857267263,74.60523815063186,76.59562404241414,80.616,81.136,81.802,80.836
15,303.40,2019,A,,11,All students,,Males,,18 and 19 years old,,,,,,,,,,FALSE,,,,1354.9630609445971,1368.0012735515882,1298.0489861636365,1464.0728239149526,1523.313780904148,1795.241775060061,1819.8636632519704,1782.4978668046824,1707.1476079669735,1661.4076975344522,1672.8968093072167,1683.5432054134255,1687.9542439322954,1686.371884493662,1653.7484115749837,1814.88,1784.474,1768.891,1786.394
16,303.40,2019,A,,12,All students,,Males,,20 and 21 years old,,,,,,,,,,FALSE,,,,1063.9056536182798,1218.584813622667,1258.9924747515051,1411.3703350317044,1657.8752787709204,1865.7925458798268,1947.8836841562359,1984.5758040401786,1959.6790913460168,1955.1772992782066,1960.0390663850885,1954.074560783512,1944.5030445153077,1914.763063465389,1888.5024863767264,2024.981,2048.363,2054.505,2044.095
17,303.40,2019,A,,13,All students,,Males,,22 to 24 years old,,,,,,,,,,FALSE,,,,1004.4528866318065,1075.4989995227645,1129.0340232681103,1221.9018148960208,1410.0950798262857,1598.5847967463997,1722.730378184015,1768.6024791294253,1863.5693694668066,1846.017215591532,1788.8767615144488,1746.404395975584,1739.0163368652247,1689.9077418057052,1652.8380518841573,1613.348,1605.859,1607.961,1638.966
18,303.40,2019,A,,14,All students,,Males,,25 to 29 years old,,,,,,,,,,FALSE,,,,795.6675046303362,983.1078355369152,1024.283497605337,908.0975841966331,1056.5963057144734,1378.2740374511545,1409.917180340833,1403.971302553025,1353.0476232224667,1356.008779922639,1378.505214680561,1382.1682490304893,1366.3595252354326,1384.7013375166307,1377.678525923714,1298.626,1290.598,1275.827,1250.729
19,303.40,2019,A,,15,All students,,Males,,30 to 34 years old,,,,,,,,,,FALSE,,,,333.1407510322888,563.9550654722755,605.4124789557641,581.1430068128402,590.6292616494954,707.1845515025987,731.2103882390143,699.8189957123151,661.2851909669553,633.9217835737022,642.9239696135369,655.3608893902606,669.6714052320629,666.711174311752,662.2670817933546,622.539,635.83,650.531,651.955
20,303.40,2019,A,,16,All students,,Males,,35 years old and over,,,,,,,,,,FALSE,,,,366.1450286718947,559.1050978962533,902.2701576212547,1076.8626191241462,1149.2492372860825,1285.2246187569929,1320.2445317341635,1290.3734917749289,1255.2156042165407,1283.1825012910422,1236.8668799189006,1208.2077684696496,1148.3551456470043,1154.2535602562284,1131.0318184046496,1015.366,1029.662,1047.038,1176.869
21,303.40,2019,A,,17,All students,,Females,,,,,,,,,,,,TRUE,,,,3537.245,6222.521000000001,7534.728,8590.520000000002,10031.55,11580.641,11973.679,11976.333999999999,11725.472000000002,11515.48,11411.561999999998,11264.385,11208.482,11206.837,11203.255999999998,11249.765,11268.206,11291.738,11484.891
22,303.40,2019,A,,18,All students,,Females,,14 to 17 years old,,,,,,,,,,FALSE,,,,137.36180191209107,150.68079313451142,87.00804260883544,73.00966086924416,119.10484714554852,112.77232909974303,108.30255909737332,116.26548807672187,122.94682667065311,130.64627704711648,121.12017799788752,119.60496559814405,131.26440212202564,135.46369678989234,129.64033398680263,123.465,124.287,125.235,123.252
23,303.40,2019,A,,19,All students,,Females,,18 and 19 years old,,,,,,,,,,FALSE,,,,1224.3148789903848,1484.1953213419692,1478.643061296054,1793.8096637158692,1920.469907232135,2213.9998028939935,2237.02784105321,2173.3181750484127,2074.41543918291,2058.9407199850234,2047.1503349884601,2048.7438060461955,2050.1449399672656,2095.9260820303493,2114.7151798752043,2275.682,2244.323,2227.433,2238.815
24,303.40,2019,A,,20,All students,,Females,,20 and 21 years old,,,,,,,,,,FALSE,,,,821.0631607825237,1176.707092963148,1333.782083601609,1593.3398402912183,1904.8564057824267,2049.7450077535345,2154.6809734277617,2284.4242912713135,2275.5267542940624,2227.5163427807734,2202.5619215129277,2193.9952024067493,2259.0140624271194,2244.7666553897548,2253.087347343059,2441.664,2470.467,2482.125,2473.154
25,303.40,2019,A,,21,All students,,Females,,22 to 24 years old,,,,,,,,,,FALSE,,,,464.1874153552422,871.0214474442325,1072.8972547980156,1377.6304286099514,1704.091712174158,1972.2561055533815,2036.1073540873017,2024.2055814778046,2086.9614695296914,2117.7298221002115,2121.542754555921,2038.3714694944028,1997.2090458473974,2000.8816691086931,2013.5972667756646,1937.491,1934.071,1938.761,1980.346
26,303.40,2019,A,,22,All students,,Females,,25 to 29 years old,,,,,,,,,,FALSE,,,,295.51572102558526,859.4657568084909,1058.5287185068944,1136.237377892508,1412.7918882669424,1703.8891167592765,1843.8053396185016,1867.624012063538,1801.7721878881516,1694.461323950081,1705.7497564308705,1783.0074193543498,1825.92649288772,1840.8498697422383,1816.374743122115,1758.987,1742.83,1720.291,1706.34
27,303.40,2019,A,,23,All students,,Females,,30 to 34 years old,,,,,,,,,,FALSE,,,,194.2948582399492,662.628733137579,778.7282423343084,751.769544986962,847.479956259022,1028.2309532307577,1073.6626090477737,1088.4726442611732,1022.4952288488814,972.0330319574631,943.3639277010423,944.7882552517635,919.2050206434432,920.166393641274,899.4125792399414,942.824,960.909,981.418,973.437
28,303.40,2019,A,,24,All students,,Females,,35 years old and over,,,,,,,,,,FALSE,,,,400.5071636942237,1017.821855170069,1725.1405968542833,1864.723483634248,2122.7552831397675,2499.7476847093126,2520.0923236680774,2422.023807801036,2341.354093585651,2314.152482179332,2270.0731268128898,2135.8738818483944,2025.7180361050282,1968.7826332977988,1976.4285496572124,1769.652,1791.319,1816.475,1989.547
29,303.40,2019,A,,25,All students,,Full-time,,,,,,,,,,,,TRUE,,,,5816.29,7097.958,7820.985,9009.6,10797.010999999999,12605.355,13087.182000000003,13002.530999999999,12734.404,12596.61,12454.464,12287.512,12125.313999999998,12076.141,11991.720999999998,12025.196,12021.884,12021.406,12143.685
30,303.40,2019,A,,26,All students,,Full-time,,14 to 17 years old,,,,,,,,,,FALSE,,,,246.36674250472436,230.88091192266364,133.53332066562263,120.98845393597327,151.65790838473626,179.42486820980412,170.27963940281285,185.04605376833868,207.41716715458233,209.5867182975906,200.41767332532476,181.9307209017124,185.73098702101777,183.37769614634354,179.46295684566263,178.141,179.294,180.702,178.12
31,303.40,2019,A,,27,All students,,Full-time,,18 and 19 years old,,,,,,,,,,FALSE,,,,2373.8520081772085,2544.2276647496446,2470.8450328387903,2822.5179950181,3026.2966120761293,3480.7663197663287,3495.961575367773,3351.46675941789,3225.8890456114077,3198.876228155938,3174.481762650459,3187.511841829504,3160.845207594635,3241.927605067986,3237.5977355392015,3390.483,3339.282,3312.981,3336.719
32,303.40,2019,A,,28,All students,,Full-time,,20 and 21 years old,,,,,,,,,,FALSE,,,,1648.7066761549193,2007.4356066998487,2136.664966133244,2452.0536644044364,2976.2625634061924,3240.833228789438,3364.0810386454923,3426.819808679283,3385.6023385034296,3327.370613472979,3326.187546208047,3290.0622865682644,3364.531445105238,3331.6252974407344,3360.9860599591125,3419.039,3460.415,3471.351,3454.822
33,303.40,2019,A,,29,All students,,Full-time,,22 to 24 years old,,,,,,,,,,FALSE,,,,904.4126202873651,1181.1188859044223,1405.4789796877976,1713.8424166230232,2122.4758043913616,2511.4493343150307,2584.8656261127353,2580.316773180274,2602.6806771288525,2649.7303750144756,2597.4913339602244,2567.589247662743,2501.6400630154994,2433.3245347471093,2374.1737606147885,2244.432,2238.254,2242.912,2289.561
34,303.40,2019,A,,30,All students,,Full-time,,25 to 29 years old,,,,,,,,,,FALSE,,,,425.756553625647,640.8022840210708,791.3170718587935,885.9437621602692,1173.8165629198686,1505.7638734061788,1605.3909011610353,1599.836438494433,1554.9320360302497,1528.471601289696,1524.629373213657,1519.2915183882287,1477.6949280246026,1480.2931211441137,1452.6195138796268,1385.479,1374.77,1357.983,1339.343
35,303.40,2019,A,,31,All students,,Full-time,,30 to 34 years old,,,,,,,,,,FALSE,,,,113.19887335770962,272.10869322585006,382.8880386609075,418.0168536143481,546.9252836847372,656.6189268344766,744.7604234919245,763.1364181631476,711.1020945238131,664.0771617284715,626.1958844967205,600.5840682109825,582.8917339077138,570.4559262340157,562.613251427877,563.664,575.017,587.741,585.651
36,303.40,2019,A,,32,All students,,Full-time,,35 years old and over,,,,,,,,,,FALSE,,,,103.99652589242595,221.38395347649896,500.2575901548445,596.2368542438513,799.5762651369741,1030.4984486787425,1121.842795818227,1095.9087482966333,1046.7806410476667,1018.4973020408491,1005.0604261455662,940.5423164385641,851.9796353312927,835.1368192196977,824.2677217337299,843.958,854.852,867.736,959.469
37,303.40,2019,A,,33,All students,,Full-time,,Males,,,,,,,,,,TRUE,,,,3504.095,3689.2439999999983,3807.7519999999995,4111.093000000001,4803.388,5632.097000000001,5838.383000000001,5792.817999999999,5708.406,5682.321999999999,5619.778,5558.446999999998,5472.798000000001,5423.955,5338.934,5349.637,5344.843,5343.275,5395.191
38,303.40,2019,A,,34,All students,,Full-time,,Males,,14 to 17 years old,,,,,,,,FALSE,,,,121.30381915417702,94.53810158227903,55.3285938305841,51.22398375010411,53.35864986924124,77.27814050873731,71.29160469804489,84.64321798269366,101.99654364635714,105.62265161883819,99.5223950198466,81.06422860379551,70.79879216713333,65.04789755165032,66.10726398204612,68.345,68.774,69.334,68.516
39,303.40,2019,A,,35,All students,,Full-time,,Males,,18 and 19 years old,,,,,,,,FALSE,,,,1261.0693984814873,1219.1861102867676,1170.8810510987312,1251.5942519442035,1339.0038955355099,1569.517549928771,1574.4578079043888,1509.8381084821467,1461.3245122289686,1422.717059071785,1401.6969841604587,1413.6230618379927,1416.0689853895985,1435.1736874643368,1406.976204909491,1458.175,1433.484,1421.821,1435.822
40,303.40,2019,A,,36,All students,,Full-time,,Males,,20 and 21 years old,,,,,,,,FALSE,,,,955.4250472933538,1046.4488654625366,1035.4536752558035,1156.3027361185684,1397.9314546941062,1536.1733006376596,1586.2303045121464,1586.4688912493448,1536.9233337727544,1542.4999258804935,1548.8098586006597,1546.469584868272,1551.7479103084904,1536.4262010241616,1546.4643595320892,1564.11,1582.296,1586.784,1578.627
41,303.40,2019,A,,37,All students,,Full-time,,Males,,22 to 24 years old,,,,,,,,FALSE,,,,686.2176087135671,716.7990852328014,767.7345247864224,833.6729891209342,982.1754044947285,1168.6457655054098,1214.6685787432627,1216.5491175647303,1253.82718826137,1269.7202038000796,1235.6651155405943,1208.4162764344503,1172.7436237881548,1128.7517538880086,1098.7364154465436,1032.176,1027.98,1029.546,1049.738
42,303.40,2019,A,,38,All students,,Full-time,,Males,,25 to 29 years old,,,,,,,,FALSE,,,,345.987774910619,390.6970431828942,433.13476647119177,409.99797183535696,505.90091972535134,660.6002918367635,714.6242703357003,727.3026578670015,727.6836423854519,734.1770757234218,732.0931086651367,709.1989051747796,689.1372977713678,692.5458027584051,683.1229265600233,671.631,667.479,659.839,646.86
43,303.40,2019,A,,39,All students,,Full-time,,Males,,30 to 34 years old,,,,,,,,FALSE,,,,76.56143562263021,141.63874923613594,170.84817110028786,186.1915585630076,225.42029742885245,279.0807947343285,300.98977068205147,298.7171027409625,277.83933905368144,256.5623187918294,241.95943950883157,250.77966113534467,252.78082895859245,256.44457225138706,244.21589604401532,249.366,254.69,260.577,261.148
44,303.40,2019,A,,40,All students,,Full-time,,Males,,35 years old and over,,,,,,,,FALSE,,,,57.52991582416544,79.93604501658429,174.3712174569787,222.10950866782608,299.59737825221004,340.8011568483303,376.1206631244064,369.2989041131207,348.8114406514168,351.0227651135523,360.0310985044723,348.8952819453646,319.5205616166626,309.56508506204955,293.31093352579137,305.834,310.14,315.374,354.48
45,303.40,2019,A,,41,All students,,Full-time,,Females,,,,,,,,,,TRUE,,,,2312.1950000000006,3408.7140000000004,4013.2330000000006,4898.507000000001,5993.6230000000005,6973.257999999999,7248.798999999999,7209.713,7025.998000000001,6914.2880000000005,6834.685999999999,6729.065,6652.516,6652.186000000001,6652.786999999998,6675.559,6677.041,6678.131,6748.494
46,303.40,2019,A,,42,All students,,Full-time,,Females,,14 to 17 years old,,,,,,,,FALSE,,,,125.06292335054732,136.34281034038463,78.20472683503851,69.76447018586916,98.29925851549503,102.1467277010668,98.98803470476795,100.40283578564502,105.42062350822519,103.9640666787524,100.89527830547814,100.86649229791689,114.93219485388445,118.32979859469322,113.35569286361651,109.796,110.52,111.368,109.604
47,303.40,2019,A,,43,All students,,Full-time,,Females,,18 and 19 years old,,,,,,,,FALSE,,,,1112.7826096957215,1325.041554462877,1299.9639817400591,1570.9237430738967,1687.2927165406197,1911.2487698375578,1921.5037674633843,1841.628650935743,1764.564533382439,1776.159169084153,1772.7847784900005,1773.8887799915112,1744.7762222050367,1806.7539176036491,1830.6215306297108,1932.308,1905.798,1891.16,1900.897
48,303.40,2019,A,,44,All students,,Full-time,,Females,,20 and 21 years old,,,,,,,,FALSE,,,,693.2816288615654,960.9867412373121,1101.2112908774402,1295.750928285868,1578.331108712086,1704.6599281517783,1777.850734133346,1840.3509174299384,1848.6790047306752,1784.8706875924854,1777.3776876073875,1743.5927016999922,1812.7835347967477,1795.1990964165725,1814.5217004270232,1854.929,1878.119,1884.567,1876.195
49,303.40,2019,A,,45,All students,,Full-time,,Females,,22 to 24 years old,,,,,,,,FALSE,,,,218.19501157379813,464.319800671621,637.7444549013753,880.169427502089,1140.300399896633,1342.8035688096206,1370.1970473694723,1363.767655615544,1348.8534888674824,1380.0101712143962,1361.8262184196299,1359.172971228293,1328.896439227345,1304.5727808591007,1275.437345168245,1212.256,1210.274,1213.366,1239.823
50,303.40,2019,A,,46,All students,,Full-time,,Females,,25 to 29 years old,,,,,,,,FALSE,,,,79.76877871502798,250.10524083817654,358.18230538760173,475.94579032491225,667.9156431945172,845.1635815694152,890.766630825335,872.5337806274315,827.2483936447978,794.2945255662744,792.5362645485203,810.0926132134492,788.5576302532347,787.7473183857086,769.4965873196035,713.848,707.291,698.144,692.483
51,303.40,2019,A,,47,All students,,Full-time,,Females,,30 to 34 years old,,,,,,,,FALSE,,,,36.6374377350794,130.46994398971415,212.03986756061965,231.82529505134053,321.5049862558847,377.5381321001481,443.770652809873,464.4193154221851,433.2627554701317,407.51484293664214,384.2364449878889,349.80440707563787,330.1109049491214,314.01135398262863,318.3973553838617,314.298,320.327,327.164,324.503
52,303.40,2019,A,,48,All students,,Full-time,,Females,,35 years old and over,,,,,,,,FALSE,,,,46.466610068260515,141.4479084599147,325.88637269786574,374.1273455760252,499.97888688476417,689.6972918304122,745.7221326938206,726.6098441835127,697.9692003962499,667.4745369272969,645.0293276410939,591.6470344931994,532.4590737146301,525.5717341576482,530.9567882079385,538.124,544.712,552.362,604.989
53,303.40,2019,A,,49,All students,,Part-time,,,,,,,,,,,,TRUE,,,,2764.5969999999998,4998.937,5997.652,6302.689,6690.464,7708.239,7932.255999999999,8008.059000000001,7910.0740000000005,7780.066999999999,7754.628000000001,7700.692,7721.59,7702.01,7654.197,7694.925,7722.244,7756.887,7971.05
54,303.40,2019,A,,50,All students,,Part-time,,14 to 17 years old,,,,,,,,,,FALSE,,,,16.36217387816331,25.92079560938318,19.34210357760398,10.342022956974326,35.612994609406584,35.998135492905114,31.932093788329226,35.63549429382813,34.59117233031192,46.541281557951,38.12380325280967,31.734175633509984,28.095713673680496,26.69123879418067,26.773001183554143,25.94,26.129,26.335,25.968
55,303.40,2019,A,,51,All students,,Part-time,,18 and 19 years old,,,,,,,,,,FALSE,,,,205.42593175777324,307.96893014391264,305.84701462090027,435.3644926127215,417.4870760601533,528.4752581877257,560.929928937407,604.3492824352054,555.6740015384762,521.4721893635374,545.5653816452179,544.7751696301171,577.2539763049259,540.3703614560252,530.8658559109863,700.079,689.515,683.343,688.49

In [15]:
tab.cell_info

Empty DataFrame
Columns: [digest_table_id, digest_table_year, digest_table_sub_id, digest_table_sub_title, is_standard_error, is_dollar, format_string, row_index, column_index, cell_note]
Index: []