In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
tabn = '217.10'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [4]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,is_total,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,217.10,2018,A,,A,FALSE,2012,,,All public schools,,,,,,,"Excludes special education, vocational, and al...",,,,,,
1,217.10,2018,A,,B,FALSE,2012,,,Instructional level,Elementary,,,,,,,,,,,,
2,217.10,2018,A,,C,FALSE,2012,,,Instructional level,Secondary,,,,,,,,,,,,
3,217.10,2018,A,,D,FALSE,2012,,,Instructional level,Combined,,,,,,,,,,,,
4,217.10,2018,A,,E,FALSE,2012,,,Community type,City,,,,,,,,,,,,
5,217.10,2018,A,,F,FALSE,2012,,,Community type,Suburban,,,,,,,,,,,,
6,217.10,2018,A,,G,FALSE,2012,,,Community type,Town,,,,,,,,,,,,
7,217.10,2018,A,,H,FALSE,2012,,,Community type,Rural,,,,,,,,,,,,
8,217.10,2018,A,,I,FALSE,2012,,,Percent of students eligible for free or reduc...,Less than 35 percent,,,,,,,,,,,,
9,217.10,2018,A,,J,FALSE,2012,,,Percent of students eligible for free or reduc...,35 to 49 percent,,,,,,,,,,,,
10,217.10,2018,A,,K,FALSE,2012,,,Percent of students eligible for free or reduc...,50 to 74 percent,,,,,,,,,,,,
11,217.10,2018,A,,L,FALSE,2012,,,Percent of students eligible for free or reduc...,75 percent or more,,,,,,,,,,,,

In [5]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,C,D,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
5,217.10,2018,A,,1,Estimated number of schools,,,,,,,,,,,,,,FALSE,2012,,,84000,(†),62600,(†),18900,(†),2400,(†),21200,(†),23500,(†),10900,(†),28400,(†),31,(†),18,(†),27,(†),23,(†)
9,217.10,2018,A,,2,Main instructional building,,"Percent of schools, by functional age",The functional age of the main instructional b...,Less than 5 years old,,,,,,,,,,FALSE,2012,,,21,1.1,19,1.2,25,2.2,27,6.8,24,2.6,23,2.2,19,2.9,17,1.9,20,2.1,23,2.9,18,2,24,2.5
10,217.10,2018,A,,3,Main instructional building,,"Percent of schools, by functional age",The functional age of the main instructional b...,5 to 14 years old,,,,,,,,,,FALSE,2012,,,38,1.2,37,1.4,39,2.3,34,7.2,33,2.5,39,2.7,37,4.1,40,2.3,40,2.2,34,3.3,39,2.6,35,3
11,217.10,2018,A,,4,Main instructional building,,"Percent of schools, by functional age",The functional age of the main instructional b...,15 to 34 years old,,,,,,,,,,FALSE,2012,,,23,1.2,25,1.6,17,1.8,28,7.5,20,2.3,20,1.8,27,3.6,28,2.3,25,2.1,22,2.9,25,2.3,20,2.7
12,217.10,2018,A,,5,Main instructional building,,"Percent of schools, by functional age",The functional age of the main instructional b...,35 or more years old,,,,,,,,,,FALSE,2012,,,18,1.2,19,1.4,18,1.7,11,4.3,22,2.4,19,2.2,17,3,15,1.9,15,2,21,2.9,17,2.1,21,2.8
14,217.10,2018,A,,6,Main instructional building,,Average years,,Since construction,,,,,,,,,,FALSE,2012,,,44,0.7,45,0.9,43,1.2,50,4.2,50,1.7,43,1.2,48,1.8,40,1.2,42,1.3,46,1.8,43,1.4,48,1.9
15,217.10,2018,A,,7,Main instructional building,,Average years,,Since major renovation,Based on schools whose main instructional buil...,,,,,,,,,FALSE,2012,,,12,0.4,12,0.5,11,0.7,12,2,11,0.7,11,0.7,14,1.2,12,0.8,11,0.6,12,1.1,12,0.8,11,0.8
18,217.10,2018,A,,8,Permanent buildings (percent of schools),,School has permanent buildings,,,,,,,,,,,,FALSE,2012,,,99,0.2,99,0.3,100,0.3,100,(#),99,0.7,100,0.4,99,0.6,100,0.3,100,0.4,99,0.6,100,(#),98,0.8
20,217.10,2018,A,,9,Permanent buildings (percent of schools),,School has permanent buildings,,Overall condition of buildings,Based on the 99 percent of public schools with...,Excellent,,,,,,,,FALSE,2012,,,20,1.1,20,1.4,20,1.5,15,5.5,17,2,23,2.2,18,3.3,20,1.8,24,2,18,2.3,20,2.1,16,2
21,217.10,2018,A,,10,Permanent buildings (percent of schools),,School has permanent buildings,,Overall condition of buildings,Based on the 99 percent of public schools with...,Good,,,,,,,,FALSE,2012,,,56,1.4,57,1.7,57,2.2,44,7,55,2.6,56,2.6,57,3.8,57,2.5,56,2.3,63,3.5,56,2.7,52,3.2
22,217.10,2018,A,,11,Permanent buildings (percent of schools),,School has permanent buildings,,Overall condition of buildings,Based on the 99 percent of public schools with...,Fair,,,,,,,,FALSE,2012,,,21,1,21,1.3,20,2,38,7.4,23,2.3,20,2.1,23,3.2,20,2,18,1.9,17,2.5,22,2,28,2.7
23,217.10,2018,A,,12,Permanent buildings (percent of schools),,School has permanent buildings,,Overall condition of buildings,Based on the 99 percent of public schools with...,Poor,,,,,,,,FALSE,2012,,,3,0.5,3,0.6,2,0.7,‡,(†),5,1.3,‡,(†),‡,(†),2,0.8,2,0.8,2,0.9,2,1,4,1.3
26,217.10,2018,A,,13,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,"Lighting, artificial",,,,,,,,FALSE,2012,,,8,0.9,8,1.1,7,1.4,‡,(†),9,1.6,7,1.4,8,2.1,9,1.4,6,1.4,7,1.8,8,1.8,11,1.9
27,217.10,2018,A,,14,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,"Lighting, natural",,,,,,,,FALSE,2012,,,16,1.1,17,1.4,16,1.7,15,5.3,16,2.2,15,2,20,3.2,16,1.9,14,1.7,17,2.7,17,2,19,2.6
28,217.10,2018,A,,15,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Heating,,,,,,,,FALSE,2012,,,14,0.9,13,1.2,16,2.1,20,6.2,16,2.1,10,1.6,14,2.4,14,1.7,12,1.6,14,2.4,14,2.2,15,2.3
29,217.10,2018,A,,16,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Air conditioning,,,,,,,,FALSE,2012,,,17,1.1,16,1.4,20,2.3,21,6.7,21,2.5,13,1.9,18,3.2,17,2,17,1.9,16,2.7,15,2.5,19,2.7
30,217.10,2018,A,,17,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Ventilation,,,,,,,,FALSE,2012,,,17,1.2,16,1.4,16,1.8,28,7.3,18,2,12,1.9,16,3.2,20,2.1,15,1.9,16,2.6,16,2,20,2.7
31,217.10,2018,A,,18,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Indoor air quality,,,,,,,,FALSE,2012,,,9,0.8,9,1,9,1.4,13,5,11,1.8,4,1,7,2.2,12,1.7,7,1.2,9,2.1,11,1.8,10,1.9
32,217.10,2018,A,,19,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Water quality,,,,,,,,FALSE,2012,,,5,0.6,5,0.8,6,1.1,16,6.4,6,1.5,3,0.9,5,1.6,7,1.3,4,1,5,1.5,6,1.4,7,1.4
33,217.10,2018,A,,20,Permanent buildings (percent of schools),,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Acoustics or noise control,,,,,,,,FALSE,2012,,,14,1,14,1.3,12,1.5,25,6.2,14,2.1,10,1.5,15,3,16,2,12,1.7,13,2.4,13,1.8,17,2.3
36,217.10,2018,A,,21,Portable (temporary) buildings (percent of sch...,,School has portable buildings,,,,,,,,,,,,FALSE,2012,,,31,1.4,33,1.8,24,2,29,6.8,40,2.8,32,2.2,27,3.6,25,2.1,25,2,30,2.9,31,2.2,39,3.4
38,217.10,2018,A,,22,Portable (temporary) buildings (percent of sch...,,School has portable buildings,,Overall condition of buildings,Based on the 31 percent of public schools with...,Excellent,,,,,,,,FALSE,2012,,,6,1.1,6,1.4,5,1.5,‡,(†),4,1.8,5,1.8,10,4.7,7,2.3,8,2.7,7,3,4,1.9,5,2
39,217.10,2018,A,,23,Portable (temporary) buildings (percent of sch...,,School has portable buildings,,Overall condition of buildings,Based on the 31 percent of public schools with...,Good,,,,,,,,FALSE,2012,,,49,2.8,49,3.2,46,4.4,56,14.2,53,4.2,51,4.9,43,7.7,44,5,51,4.8,53,6.1,45,4.4,48,5
40,217.10,2018,A,,24,Portable (temporary) buildings (percent of sch...,,School has portable buildings,,Overall condition of buildings,Based on the 31 percent of public schools with...,Fair,,,,,,,,FALSE,2012,,,36,2.4,36,2.9,43,4.8,‡,(†),34,4.1,38,4.8,38,7.5,36,4.8,29,4.1,36,5.9,41,4.2,38,4.6
41,217.10,2018,A,,25,Portable (temporary) buildings (percent of sch...,,School has portable buildings,,Overall condition of buildings,Based on the 31 percent of public schools with...,Poor,,,,,,,,FALSE,2012,,,9,1.4,9,1.7,7,2.3,‡,(†),8,2.6,6,2,9,4.1,13,3.5,12,3.2,‡,(†),10,3.2,8,3
44,217.10,2018,A,,26,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,"Lighting, artificial",,,,,,,,FALSE,2012,,,11,1.8,11,2.1,12,3.3,#,(†),10,2.9,6,2.6,14,5.7,15,4,10,3,8,3.5,12,3.3,12,3.3
45,217.10,2018,A,,27,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,"Lighting, natural",,,,,,,,FALSE,2012,,,28,2.5,29,3,28,4.3,‡,(†),26,4.2,26,4.4,41,8,28,4.4,26,4.1,28,4.9,29,4.8,30,4.5
46,217.10,2018,A,,28,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Heating,,,,,,,,FALSE,2012,,,12,1.8,11,2,16,3.5,#,(†),11,2.9,7,2.4,17,5.7,16,4,13,3.5,8,3.5,15,3.5,10,3.1
47,217.10,2018,A,,29,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Air conditioning,,,,,,,,FALSE,2012,,,15,2.2,16,2.6,14,3.3,‡,(†),15,3.6,12,3.1,14,5.3,18,4.3,17,3.9,13,4.1,16,3.9,14,3.7
48,217.10,2018,A,,30,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Ventilation,,,,,,,,FALSE,2012,,,19,2.2,19,2.6,22,3.9,‡,(†),18,3.7,14,3.1,26,6.7,24,4.4,18,3.9,18,5.7,23,4.6,18,4
49,217.10,2018,A,,31,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Indoor air quality,,,,,,,,FALSE,2012,,,16,2,17,2.3,14,3,#,(†),17,3.6,11,2.8,18,5.5,19,4.2,14,3.4,15,4.4,19,4.1,16,3.6
50,217.10,2018,A,,32,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Water quality,,,,,,,,FALSE,2012,,,10,1.7,10,2,8,3.1,‡,(†),7,2.7,7,2.9,16,6.7,14,4.6,9,3.8,‡,(†),11,3.8,14,3.8
51,217.10,2018,A,,33,Portable (temporary) buildings (percent of sch...,,,,Environmental factors are unsatisfactory,Based on schools with the specified environmen...,Acoustics or noise control,,,,,,,,FALSE,2012,,,21,2.5,21,2.9,21,4.1,‡,(†),19,3.6,17,3.9,24,7.1,26,4.6,19,4.2,11,4.2,26,4.6,23,4.7

In [6]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,has_SE,location_in,year_in,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,217.10,2018,A,,TRUE,,Title,Functional age of public schools' main instruc...,[Standard errors appear in parentheses],Functional age of main instructional building;...,Detail may not sum to totals because of rounding.,"U.S. Department of Education, National Center ...",This table was prepared June 2014.

In [7]:
tab.cell_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,column_index,cell_note
0,217.10,2018,A,,1,C,Not applicable.
1,217.10,2018,A,,1,F,Not applicable.
2,217.10,2018,A,,1,H,Not applicable.
3,217.10,2018,A,,1,J,Not applicable.
4,217.10,2018,A,,1,L,Not applicable.
5,217.10,2018,A,,1,N,Not applicable.
6,217.10,2018,A,,1,P,Not applicable.
7,217.10,2018,A,,1,R,Not applicable.
8,217.10,2018,A,,1,T,Not applicable.
9,217.10,2018,A,,1,V,Not applicable.
10,217.10,2018,A,,1,X,Not applicable.
11,217.10,2018,A,,1,Z,Not applicable.
12,217.10,2018,A,,5,I,Interpret data with caution. The coefficient o...
13,217.10,2018,A,,8,J,Rounds to zero.
14,217.10,2018,A,,8,X,Rounds to zero.
15,217.10,2018,A,,9,I,Interpret data with caution. The coefficient o...
16,217.10,2018,A,,12,G,Interpret data with caution. The coefficient o...
17,217.10,2018,A,,12,I,Reporting standards not met. Either there are ...
18,217.10,2018,A,,12,J,Not applicable.
19,217.10,2018,A,,12,M,Reporting standards not met. Either there are ...
20,217.10,2018,A,,12,N,Not applicable.
21,217.10,2018,A,,12,O,Reporting standards not met. Either there are ...
22,217.10,2018,A,,12,P,Not applicable.
23,217.10,2018,A,,12,Q,Interpret data with caution. The coefficient o...
24,217.10,2018,A,,12,S,Interpret data with caution. The coefficient o...
25,217.10,2018,A,,12,U,Interpret data with caution. The coefficient o...
26,217.10,2018,A,,12,W,Interpret data with caution. The coefficient o...
27,217.10,2018,A,,13,I,Reporting standards not met. Either there are ...
28,217.10,2018,A,,13,J,Not applicable.
29,217.10,2018,A,,14,I,Interpret data with caution. The coefficient o...
30,217.10,2018,A,,15,I,Interpret data with caution. The coefficient o...
31,217.10,2018,A,,16,I,Interpret data with caution. The coefficient o...
32,217.10,2018,A,,18,I,Interpret data with caution. The coefficient o...
33,217.10,2018,A,,19,I,Interpret data with caution. The coefficient o...
34,217.10,2018,A,,22,G,Interpret data with caution. The coefficient o...
35,217.10,2018,A,,22,I,Reporting standards not met. Either there are ...
36,217.10,2018,A,,22,J,Not applicable.
37,217.10,2018,A,,22,K,Interpret data with caution. The coefficient o...
38,217.10,2018,A,,22,M,Interpret data with caution. The coefficient o...
39,217.10,2018,A,,22,O,Interpret data with caution. The coefficient o...
40,217.10,2018,A,,22,Q,Interpret data with caution. The coefficient o...
41,217.10,2018,A,,22,S,Interpret data with caution. The coefficient o...
42,217.10,2018,A,,22,U,Interpret data with caution. The coefficient o...
43,217.10,2018,A,,22,W,Interpret data with caution. The coefficient o...
44,217.10,2018,A,,22,Y,Interpret data with caution. The coefficient o...
45,217.10,2018,A,,24,I,Reporting standards not met. Either there are ...
46,217.10,2018,A,,24,J,Not applicable.
47,217.10,2018,A,,25,G,Interpret data with caution. The coefficient o...
48,217.10,2018,A,,25,I,Reporting standards not met. Either there are ...
49,217.10,2018,A,,25,J,Not applicable.
50,217.10,2018,A,,25,K,Interpret data with caution. The coefficient o...
51,217.10,2018,A,,25,M,Interpret data with caution. The coefficient o...
52,217.10,2018,A,,25,O,Interpret data with caution. The coefficient o...
53,217.10,2018,A,,25,U,Reporting standards not met. Either there are ...
54,217.10,2018,A,,25,V,Not applicable.
55,217.10,2018,A,,25,W,Interpret data with caution. The coefficient o...
56,217.10,2018,A,,25,Y,Interpret data with caution. The coefficient o...
57,217.10,2018,A,,26,I,Rounds to zero.
58,217.10,2018,A,,26,J,Not applicable.
59,217.10,2018,A,,26,M,Interpret data with caution. The coefficient o...
60,217.10,2018,A,,26,O,Interpret data with caution. The coefficient o...
61,217.10,2018,A,,26,S,Interpret data with caution. The coefficient o...
62,217.10,2018,A,,26,U,Interpret data with caution. The coefficient o...
63,217.10,2018,A,,27,I,Reporting standards not met. Either there are ...
64,217.10,2018,A,,27,J,Not applicable.
65,217.10,2018,A,,28,I,Rounds to zero.
66,217.10,2018,A,,28,J,Not applicable.
67,217.10,2018,A,,28,M,Interpret data with caution. The coefficient o...
68,217.10,2018,A,,28,O,Interpret data with caution. The coefficient o...
69,217.10,2018,A,,28,U,Interpret data with caution. The coefficient o...
70,217.10,2018,A,,29,I,Reporting standards not met. Either there are ...
71,217.10,2018,A,,29,J,Not applicable.
72,217.10,2018,A,,29,O,Interpret data with caution. The coefficient o...
73,217.10,2018,A,,29,U,Interpret data with caution. The coefficient o...
74,217.10,2018,A,,30,I,Reporting standards not met. Either there are ...
75,217.10,2018,A,,30,J,Not applicable.
76,217.10,2018,A,,30,U,Interpret data with caution. The coefficient o...
77,217.10,2018,A,,31,I,Rounds to zero.
78,217.10,2018,A,,31,J,Not applicable.
79,217.10,2018,A,,31,O,Interpret data with caution. The coefficient o...
80,217.10,2018,A,,31,U,Interpret data with caution. The coefficient o...
81,217.10,2018,A,,32,G,Interpret data with caution. The coefficient o...
82,217.10,2018,A,,32,I,Reporting standards not met. Either there are ...
83,217.10,2018,A,,32,J,Not applicable.
84,217.10,2018,A,,32,K,Interpret data with caution. The coefficient o...
85,217.10,2018,A,,32,M,Interpret data with caution. The coefficient o...
86,217.10,2018,A,,32,O,Interpret data with caution. The coefficient o...
87,217.10,2018,A,,32,Q,Interpret data with caution. The coefficient o...
88,217.10,2018,A,,32,S,Interpret data with caution. The coefficient o...
89,217.10,2018,A,,32,U,Reporting standards not met. Either there are ...
90,217.10,2018,A,,32,V,Not applicable.
91,217.10,2018,A,,32,W,Interpret data with caution. The coefficient o...
92,217.10,2018,A,,33,I,Reporting standards not met. Either there are ...
93,217.10,2018,A,,33,J,Not applicable.
94,217.10,2018,A,,33,O,Interpret data with caution. The coefficient o...
95,217.10,2018,A,,33,U,Interpret data with caution. The coefficient o...