In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [13]:
tabn = '325.80'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [14]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,has_SE,location_in,year_in,year,location,location_info,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,325.80,2019,A,,FALSE,Title,Row,,United States,,Degrees in psychology conferred by postseconda...,,Year,Data are for postsecondary institutions partic...,"U.S. Department of Education, National Center ...",This table was prepared September 2019.

In [15]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,standard_error,is_dollar,format_string,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,325.80,2019,A,,A,FALSE,,,,,,Bachelor's degrees,Total,Number,,,,,,,,,,,
1,325.80,2019,A,,B,FALSE,,,,,,Bachelor's degrees,Total,Annual percent change,,,,,,,,,,,
2,325.80,2019,A,,C,FALSE,,,,,,Bachelor's degrees,Males,,,,,,,,,,,,
3,325.80,2019,A,,D,FALSE,,,,,,Bachelor's degrees,Females,,,,,,,,,,,,
4,325.80,2019,A,,E,FALSE,,,,,,Bachelor's degrees,Females as a percent of total,,,,,,,,,,,,
5,325.80,2019,A,,F,FALSE,,,,,,Master's degrees,Total,,,,,,,,,,,,
6,325.80,2019,A,,G,FALSE,,,,,,Master's degrees,Males,,,,,,,,,,,,
7,325.80,2019,A,,H,FALSE,,,,,,Master's degrees,Females,,,,,,,,,,,,
8,325.80,2019,A,,I,FALSE,,,,,,Doctor's degrees,Total,,,,,,,,,,,,
9,325.80,2019,A,,J,FALSE,,,,,,Doctor's degrees,Males,,,,,,,,,,,,
10,325.80,2019,A,,K,FALSE,,,,,,Doctor's degrees,Females,,,,,,,,,,,,

In [16]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,B,C,D,E,F,G,H,I,J,K
5,325.80,2019,A,,1,1949-50,,,,,,,,,,,,,,FALSE,1949-50,,,9569.0,†,6055.0,3514.0,36.72275054864667,1316.0,948.0,368.0,283.0,241.0,42.0
6,325.80,2019,A,,2,1959-60,,,,,,,,,,,,,,FALSE,1959-60,,,8061.0,†,4773.0,3288.0,40.788983997022704,1406.0,981.0,425.0,641.0,544.0,97.0
7,325.80,2019,A,,3,1967-68,,,,,,,,,,,,,,FALSE,1967-68,,,23819.0,†,13792.0,10027.0,42.09664553507704,3479.0,2321.0,1158.0,1268.0,982.0,286.0
8,325.80,2019,A,,4,1969-70,,,,,,,,,,,,,,FALSE,1969-70,,,33679.0,†,19077.0,14602.0,43.35639419222661,5158.0,2975.0,2183.0,1962.0,1505.0,457.0
10,325.80,2019,A,,5,1970-71,,,,,,,,,,,,,,FALSE,1970-71,,,38187.0,13.385195522432374,21227.0,16960.0,44.41302013774321,5717.0,3395.0,2322.0,2144.0,1629.0,515.0
11,325.80,2019,A,,6,1971-72,,,,,,,,,,,,,,FALSE,1971-72,,,43433.0,13.737659412889203,23352.0,20081.0,46.23443004167338,6764.0,3934.0,2830.0,2277.0,1694.0,583.0
12,325.80,2019,A,,7,1972-73,,,,,,,,,,,,,,FALSE,1972-73,,,47940.0,10.376902355351922,25117.0,22823.0,47.607425949103046,7619.0,4325.0,3294.0,2550.0,1797.0,753.0
13,325.80,2019,A,,8,1973-74,,,,,,,,,,,,,,FALSE,1973-74,,,52139.0,8.75886524822695,25868.0,26271.0,50.38646694413011,8796.0,4983.0,3813.0,2872.0,1987.0,885.0
14,325.80,2019,A,,9,1974-75,,,,,,,,,,,,,,FALSE,1974-75,,,51245.0,-1.7146473848750454,24284.0,26961.0,52.61196214264806,9394.0,5035.0,4359.0,2913.0,1979.0,934.0
16,325.80,2019,A,,10,1975-76,,,,,,,,,,,,,,FALSE,1975-76,,,50278.0,-1.8870133671577713,22898.0,27380.0,54.45721786865031,10167.0,5136.0,5031.0,3157.0,2115.0,1042.0
17,325.80,2019,A,,11,1976-77,,,,,,,,,,,,,,FALSE,1976-77,,,47861.0,-4.807271570070409,20627.0,27234.0,56.902279517770204,10859.0,5293.0,5566.0,3386.0,2127.0,1259.0
18,325.80,2019,A,,12,1977-78,,,,,,,,,,,,,,FALSE,1977-78,,,44879.0,-6.230542612983432,18422.0,26457.0,58.951848303215314,10282.0,4670.0,5612.0,3164.0,1974.0,1190.0
19,325.80,2019,A,,13,1978-79,,,,,,,,,,,,,,FALSE,1978-79,,,42697.0,-4.861962164932374,16540.0,26157.0,61.261915357050846,10132.0,4405.0,5727.0,3228.0,1895.0,1333.0
20,325.80,2019,A,,14,1979-80,,,,,,,,,,,,,,FALSE,1979-80,,,42093.0,-1.414619294095604,15440.0,26653.0,63.319316751003726,9938.0,4096.0,5842.0,3395.0,1921.0,1474.0
22,325.80,2019,A,,15,1980-81,,,,,,,,,,,,,,FALSE,1980-81,,,41068.0,-2.4350842182785737,14332.0,26736.0,65.10178240966202,10223.0,4066.0,6157.0,3576.0,2002.0,1574.0
23,325.80,2019,A,,16,1981-82,,,,,,,,,,,,,,FALSE,1981-82,,,41212.0,0.3506379662997955,13645.0,27567.0,66.89071144326894,9947.0,3823.0,6124.0,3461.0,1856.0,1605.0
24,325.80,2019,A,,17,1982-83,,,,,,,,,,,,,,FALSE,1982-83,,,40460.0,-1.8247112491507327,13131.0,27329.0,67.54572417202175,9981.0,3647.0,6334.0,3602.0,1838.0,1764.0
25,325.80,2019,A,,18,1983-84,,,,,,,,,,,,,,FALSE,1983-84,,,39955.0,-1.2481463173504697,12812.0,27143.0,67.93392566637468,9525.0,3400.0,6125.0,3535.0,1774.0,1761.0
26,325.80,2019,A,,19,1984-85,,,,,,,,,,,,,,FALSE,1984-85,,,39900.0,-0.13765486171943436,12706.0,27194.0,68.15538847117794,9891.0,3452.0,6439.0,3447.0,1739.0,1708.0
28,325.80,2019,A,,20,1985-86,,,,,,,,,,,,,,FALSE,1985-86,,,40628.0,1.8245614035087718,12605.0,28023.0,68.97459879885794,9845.0,3347.0,6498.0,3593.0,1724.0,1869.0
29,325.80,2019,A,,21,1986-87,,,,,,,,,,,,,,FALSE,1986-87,,,43152.0,6.212464310327852,13395.0,29757.0,68.95856507230256,11000.0,3516.0,7484.0,4062.0,1801.0,2261.0
30,325.80,2019,A,,22,1987-88,,,,,,,,,,,,,,FALSE,1987-88,,,45371.0,5.14228772710419,13579.0,31792.0,70.07119084878006,10488.0,3256.0,7232.0,3973.0,1783.0,2190.0
31,325.80,2019,A,,23,1988-89,,,,,,,,,,,,,,FALSE,1988-89,,,49083.0,8.181437482092086,14265.0,34818.0,70.9369842919137,11329.0,3465.0,7864.0,4143.0,1773.0,2370.0
32,325.80,2019,A,,24,1989-90,,,,,,,,,,,,,,FALSE,1989-90,,,53952.0,9.919931544526618,15336.0,38616.0,71.57473309608541,10730.0,3377.0,7353.0,3811.0,1566.0,2245.0
34,325.80,2019,A,,25,1990-91,,,,,,,,,,,,,,FALSE,1990-91,,,58655.0,8.717007710557532,16067.0,42588.0,72.60762083368851,11349.0,3329.0,8020.0,3932.0,1520.0,2412.0
35,325.80,2019,A,,26,1991-92,,,,,,,,,,,,,,FALSE,1991-92,,,63683.0,8.572159236211746,17062.0,46621.0,73.20792048113312,11659.0,3335.0,8324.0,3814.0,1490.0,2324.0
36,325.80,2019,A,,27,1992-93,,,,,,,,,,,,,,FALSE,1992-93,,,66931.0,5.100262236389617,17942.0,48989.0,73.19328861065874,12518.0,3380.0,9138.0,4100.0,1570.0,2530.0
37,325.80,2019,A,,28,1993-94,,,,,,,,,,,,,,FALSE,1993-94,,,69419.0,3.7172610598975067,18668.0,50751.0,73.10822685431943,13723.0,3763.0,9960.0,4021.0,1497.0,2524.0
38,325.80,2019,A,,29,1994-95,,,,,,,,,,,,,,FALSE,1994-95,,,72233.0,4.05364525562166,19570.0,52663.0,72.90712001439785,15378.0,4210.0,11168.0,4252.0,1562.0,2690.0
40,325.80,2019,A,,30,1995-96,,,,,,,,,,,,,,FALSE,1995-96,,,73416.0,1.6377555964725263,19836.0,53580.0,72.98136645962732,15152.0,4090.0,11062.0,4141.0,1380.0,2761.0
41,325.80,2019,A,,31,1996-97,,,,,,,,,,,,,,FALSE,1996-97,,,74308.0,1.2149940067560205,19408.0,54900.0,73.88168164935135,15769.0,4155.0,11614.0,4507.0,1495.0,3012.0
42,325.80,2019,A,,32,1997-98,,,,,,,,,,,,,,FALSE,1997-98,,,74107.0,-0.2704957743446197,18976.0,55131.0,74.39378196391704,15142.0,3978.0,11164.0,4541.0,1470.0,3071.0
43,325.80,2019,A,,33,1998-99,,,,,,,,,,,,,,FALSE,1998-99,,,73747.0,-0.4857840689813378,18376.0,55371.0,75.08237623225351,15560.0,3959.0,11601.0,4678.0,1528.0,3150.0
44,325.80,2019,A,,34,1999-2000,,,,,,,,,,,,,,FALSE,1999-2000,,,74194.0,0.6061263509024096,17451.0,56743.0,76.4792301264253,15740.0,3821.0,11919.0,4731.0,1529.0,3202.0
46,325.80,2019,A,,35,2000-01,,,,,,,,,,,,,,FALSE,2000-01,,,73645.0,-0.7399520176833706,16585.0,57060.0,77.47980175164642,16539.0,3892.0,12647.0,5091.0,1598.0,3493.0
47,325.80,2019,A,,36,2001-02,,,,,,,,,,,,,,FALSE,2001-02,,,76775.0,4.250118813225609,17284.0,59491.0,77.48746336698143,16357.0,3814.0,12543.0,4759.0,1503.0,3256.0
48,325.80,2019,A,,37,2002-03,,,,,,,,,,,,,,FALSE,2002-03,,,78650.0,2.44220123738196,17514.0,61136.0,77.73172282263191,17161.0,3839.0,13322.0,4835.0,1483.0,3352.0
49,325.80,2019,A,,38,2003-04,,,,,,,,,,,,,,FALSE,2003-04,,,82098.0,4.38397965670693,18193.0,63905.0,77.83989865770177,17898.0,3789.0,14109.0,4827.0,1496.0,3331.0
50,325.80,2019,A,,39,2004-05,,,,,,,,,,,,,,FALSE,2004-05,,,85614.0,4.282686545348242,19000.0,66614.0,77.80736795383932,18830.0,3900.0,14930.0,5106.0,1466.0,3640.0
52,325.80,2019,A,,40,2005-06,,,,,,,,,,,,,,FALSE,2005-06,,,88132.0,2.941107762749083,19865.0,68267.0,77.45994644397041,19775.0,4079.0,15696.0,4921.0,1347.0,3574.0
53,325.80,2019,A,,41,2006-07,,,,,,,,,,,,,,FALSE,2006-07,,,90073.0,2.20237825080561,20336.0,69737.0,77.4227570970213,21096.0,4273.0,16823.0,5156.0,1383.0,3773.0
54,325.80,2019,A,,42,2007-08,,,,,,,,,,,,,,FALSE,2007-08,,,92562.0,2.7633142007038733,21191.0,71371.0,77.10615587390073,21420.0,4354.0,17066.0,5296.0,1440.0,3856.0
55,325.80,2019,A,,43,2008-09,,,,,,,,,,,,,,FALSE,2008-09,,,94273.0,1.8484907413409393,21490.0,72783.0,77.20450181918471,23415.0,4789.0,18626.0,5477.0,1478.0,3999.0
56,325.80,2019,A,,44,2009-10,,,,,,,,,,,,,,FALSE,2009-10,,,97215.0,3.1207238551865326,22262.0,74953.0,77.10024173224296,23763.0,4799.0,18964.0,5540.0,1478.0,4062.0
58,325.80,2019,A,,45,2010-11,,,,,,,,,,,,,,FALSE,2010-11,,,100906.0,3.7967391863395568,23230.0,77676.0,76.9785741184865,25062.0,5127.0,19935.0,5851.0,1481.0,4370.0
59,325.80,2019,A,,46,2011-12,,,,,,,,,,,,,,FALSE,2011-12,,,109099.0,8.11943789269221,25420.0,83679.0,76.70006141211194,27052.0,5482.0,21570.0,5936.0,1525.0,4411.0
60,325.80,2019,A,,47,2012-13,,,,,,,,,,,,,,FALSE,2012-13,,,114446.0,4.901053171889751,26814.0,87632.0,76.57060971986789,27787.0,5715.0,22072.0,6326.0,1628.0,4698.0
61,325.80,2019,A,,48,2013-14,,,,,,,,,,,,,,FALSE,2013-14,,,117312.0,2.5042378064764166,27306.0,90006.0,76.72360883797053,27926.0,5729.0,22197.0,6634.0,1680.0,4954.0
62,325.80,2019,A,,49,2014-15,,,,,,,,,,,,,,FALSE,2014-15,,,117573.0,0.22248363338788874,26803.0,90770.0,77.20309935104149,26772.0,5538.0,21234.0,6583.0,1624.0,4959.0
64,325.80,2019,A,,50,2015-16,,,,,,,,,,,,,,FALSE,2015-16,,,117447.0,-0.10716746191727691,26277.0,91170.0,77.62650386983064,27645.0,5571.0,22074.0,6540.0,1658.0,4882.0
65,325.80,2019,A,,51,2016-17,,,,,,,,,,,,,,FALSE,2016-17,,,116859.0,-0.5006513576336561,25520.0,91339.0,78.16171625634311,27539.0,5586.0,21953.0,6702.0,1691.0,5011.0
66,325.80,2019,A,,52,2017-18,,,,,,,,,,,,,,FALSE,2017-18,,,116432.0,-0.36539761593030917,24578.0,91854.0,78.89068297375292,27841.0,5526.0,22315.0,6275.0,1649.0,4626.0
69,325.80,2019,A,,53,Percent change,,2007-08 to 2012-13,,,,,,,,,,,,FALSE,2007-08 to 2012-13,,,23.64253149240509,†,26.534849700344488,22.783763713553125,†,29.724556489262373,31.25861276986679,29.33317707722958,19.448640483383688,13.055555555555557,21.83609958506224
70,325.80,2019,A,,54,Percent change,,2012-13 to 2017-18,,,,,,,,,,,,FALSE,2012-13 to 2017-18,,,1.7353162190028484,†,-8.338927425971507,4.817874748950155,†,0.19433548062043401,-3.3070866141732282,1.1009423704240666,-0.8061966487511856,1.2899262899262898,-1.532567049808429

In [17]:
tab.cell_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,standard_error,is_dollar,format_string,row_index,column_index,cell_note
0,325.80,2019,A,,FALSE,,,1,B,Not applicable.
1,325.80,2019,A,,FALSE,,,2,B,Not applicable.
2,325.80,2019,A,,FALSE,,,3,B,Not applicable.
3,325.80,2019,A,,FALSE,,,4,B,Not applicable.
4,325.80,2019,A,,FALSE,,,53,B,Not applicable.
5,325.80,2019,A,,FALSE,,,53,E,Not applicable.
6,325.80,2019,A,,FALSE,,,54,B,Not applicable.
7,325.80,2019,A,,FALSE,,,54,E,Not applicable.