In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
tabn = '216.75'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [8]:
tab.title

'Public elementary schools, by grade span, average school enrollment, and state or jurisdiction: 2017-18 '

In [33]:
re.search(r": (\d{4}-\d{2})\s*$", tab.title)

In [35]:
re.search(r":\s+(\d{4}-\d{2})\s*$", tab.title)

In [32]:
re.match(r":\s+(\d{4}-\d{2})\s*$", "jurisdiction: 1234-56 ")

In [4]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,digest_table_sub_title_note,has_SE,location_in,year_in,year,location,location_info,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,216.75,2019,A,,,FALSE,Row,Title,,,,"Public elementary schools, by grade span, aver...",,State or jurisdiction,Includes schools beginning with grade 6 or bel...,"U.S. Department of Education, National Center ...",This table was prepared December 2019.

In [5]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,is_standard_error,is_dollar,format_string,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,216.75,2019,A,,A,FALSE,,,,,,"Total, all elementary schools",,,,,,,,,,,,,
1,216.75,2019,A,,B,FALSE,,,,,,"Total, all regular elementary schools",,,,,,,Excludes special education and alternative sch...,,,,,,
2,216.75,2019,A,,C,FALSE,,,,,,"Schools, by grade span","Prekindergarten, kindergarten, or grade 1 to g...",,,,,,,,,,,,
3,216.75,2019,A,,D,FALSE,,,,,,"Schools, by grade span","Prekindergarten, kindergarten, or grade 1 to g...",,,,,,,,,,,,
4,216.75,2019,A,,E,FALSE,,,,,,"Schools, by grade span","Prekindergarten, kindergarten, or grade 1 to g...",,,,,,,,,,,,
5,216.75,2019,A,,F,FALSE,,,,,,"Schools, by grade span","Prekindergarten, kindergarten, or grade 1 to g...",,,,,,,,,,,,
6,216.75,2019,A,,G,FALSE,,,,,,"Schools, by grade span","Grade 4, 5, or 6 to grade 6, 7, or 8",,,,,,,,,,,,
7,216.75,2019,A,,H,FALSE,,,,,,"Schools, by grade span",Other grade spans,,,,,,,,,,,,
8,216.75,2019,A,,I,FALSE,,,,,,Average school enrollment,All elementary schools,,,,,,Average for schools reporting enrollment data....,,,,,,
9,216.75,2019,A,,J,FALSE,,,,,,Average school enrollment,Regular elementary schools,,,,,,Average for schools reporting enrollment data....,Excludes special education and alternative sch...,,,,,

In [6]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,B,C,D,E,F,G,H,I,J
4,216.75,2019,A,,1,United States,,,,,,,,,,,,,,TRUE,,United States,State or jurisdiction,67408,66436,4985,25906,9470,6826,13437,6784,482.70978958364424,487.08091490036713
5,216.75,2019,A,,2,United States,,Alabama,,,,,,,,,,,,FALSE,,Alabama,State or jurisdiction,922,913,95,288,140,62,215,122,497.724,499.877
6,216.75,2019,A,,3,United States,,Alaska,,,,,,,,,,,,FALSE,,Alaska,State or jurisdiction,198,198,0,42,96,22,25,13,334.692,334.692
7,216.75,2019,A,,4,United States,,Arizona,,,,,,,,,,,,FALSE,,Arizona,State or jurisdiction,1391,1374,48,236,376,484,174,73,504.92,506.703
8,216.75,2019,A,,5,United States,,Arkansas,,,,,,,,,,,,FALSE,,Arkansas,State or jurisdiction,689,687,129,142,154,7,153,104,450.431,451.562
9,216.75,2019,A,,6,United States,,California,,,,,,,,,,,,FALSE,,California,State or jurisdiction,7028,6882,118,2569,2043,1068,1057,173,545.492,552.661
10,216.75,2019,A,,7,United States,,Colorado,,,,,,,,,,,,FALSE,,Colorado,State or jurisdiction,1337,1332,26,641,188,137,246,99,433.895,434.583
11,216.75,2019,A,,8,United States,,Connecticut,,,,,,,,,,,,FALSE,,Connecticut,State or jurisdiction,784,779,87,270,67,104,155,101,424.656,427.05
12,216.75,2019,A,,9,United States,,Delaware,,,,,,,,,,,,FALSE,,Delaware,State or jurisdiction,165,156,14,83,4,7,38,19,538.235,553.462
13,216.75,2019,A,,10,United States,,District of Columbia,,,,,,,,,,,,FALSE,,District of Columbia,State or jurisdiction,177,177,21,73,1,33,33,16,369.367,369.367
14,216.75,2019,A,,11,United States,,Florida,,,,,,,,,,,,FALSE,,Florida,State or jurisdiction,2843,2786,31,1656,123,338,568,127,670.34,682.343
15,216.75,2019,A,,12,United States,,Georgia,,,,,,,,,,,,FALSE,,Georgia,State or jurisdiction,1775,1774,36,1060,22,42,464,151,683.626,683.997
16,216.75,2019,A,,13,United States,,Hawaii,,,,,,,,,,,,FALSE,,Hawaii,State or jurisdiction,212,212,0,87,85,10,28,2,533.571,533.571
17,216.75,2019,A,,14,United States,,Idaho,,,,,,,,,,,,FALSE,,Idaho,State or jurisdiction,466,454,34,163,126,33,86,24,393.498,402.108
18,216.75,2019,A,,15,United States,,Illinois,,,,,,,,,,,,FALSE,,Illinois,State or jurisdiction,3086,3058,283,774,285,660,580,504,425.585,429.118
19,216.75,2019,A,,16,United States,,Indiana,,,,,,,,,,,,FALSE,,Indiana,State or jurisdiction,1370,1367,167,469,294,44,267,129,475.836,476.68
20,216.75,2019,A,,17,United States,,Iowa,,,,,,,,,,,,FALSE,,Iowa,State or jurisdiction,935,934,112,322,137,10,226,128,355.032,355.312
21,216.75,2019,A,,18,United States,,Kansas,,,,,,,,,,,,FALSE,,Kansas,State or jurisdiction,917,915,67,371,180,51,190,58,349.621,350.32
22,216.75,2019,A,,19,United States,,Kentucky,,,,,,,,,,,,FALSE,,Kentucky,State or jurisdiction,966,954,31,466,104,76,194,95,475.507,480.81
23,216.75,2019,A,,20,United States,,Louisiana,,,,,,,,,,,,FALSE,,Louisiana,State or jurisdiction,959,958,79,307,108,133,201,131,474.044,474.435
24,216.75,2019,A,,21,United States,,Maine,,,,,,,,,,,,FALSE,,Maine,State or jurisdiction,439,439,46,96,55,90,77,75,269.162,269.162
25,216.75,2019,A,,22,United States,,Maryland,,,,,,,,,,,,FALSE,,Maryland,State or jurisdiction,1120,1107,11,685,51,102,222,49,558.18,563.41
26,216.75,2019,A,,23,United States,,Massachusetts,,,,,,,,,,,,FALSE,,Massachusetts,State or jurisdiction,1413,1408,178,486,115,103,285,246,434.713,435.338
27,216.75,2019,A,,24,United States,,Michigan,,,,,,,,,,,,FALSE,,Michigan,State or jurisdiction,2272,2175,218,760,185,246,453,410,421.171,424.411
28,216.75,2019,A,,25,United States,,Minnesota,,,,,,,,,,,,FALSE,,Minnesota,State or jurisdiction,1379,1201,115,433,238,80,274,239,426.578,467.728
29,216.75,2019,A,,26,United States,,Mississippi,,,,,,,,,,,,FALSE,,Mississippi,State or jurisdiction,614,614,69,140,87,40,153,125,494.616,494.616
30,216.75,2019,A,,27,United States,,Missouri,,,,,,,,,,,,FALSE,,Missouri,State or jurisdiction,1611,1603,143,517,294,115,322,220,371.664,372.772
31,216.75,2019,A,,28,United States,,Montana,,,,,,,,,,,,FALSE,,Montana,State or jurisdiction,496,493,17,76,185,110,74,34,193.439,193.789
32,216.75,2019,A,,29,United States,,Nebraska,,,,,,,,,,,,FALSE,,Nebraska,State or jurisdiction,731,727,46,198,239,19,110,119,298.442,298.442
33,216.75,2019,A,,30,United States,,Nevada,,,,,,,,,,,,FALSE,,Nevada,State or jurisdiction,513,504,11,283,72,32,98,17,633.417,642.795
34,216.75,2019,A,,31,United States,,New Hampshire,,,,,,,,,,,,FALSE,,New Hampshire,State or jurisdiction,382,382,51,113,37,54,83,44,313.189,313.189
35,216.75,2019,A,,32,United States,,New Jersey,,,,,,,,,,,,FALSE,,New Jersey,State or jurisdiction,1952,1932,263,555,133,287,369,345,456.172,459.836
36,216.75,2019,A,,33,United States,,New Mexico,,,,,,,,,,,,FALSE,,New Mexico,State or jurisdiction,600,596,20,250,109,33,130,58,361.375,363.187
37,216.75,2019,A,,34,United States,,New York,,,,,,,,,,,,FALSE,,New York,State or jurisdiction,3286,3262,287,1293,343,292,716,355,514.323,515.62
38,216.75,2019,A,,35,United States,,North Carolina,,,,,,,,,,,,FALSE,,North Carolina,State or jurisdiction,1939,1927,77,1100,53,141,468,100,527.215,530.133
39,216.75,2019,A,,36,United States,,North Dakota,,,,,,,,,,,,FALSE,,North Dakota,State or jurisdiction,305,305,13,88,95,67,33,9,247.016,247.016
40,216.75,2019,A,,37,United States,,Ohio,,,,,,,,,,,,FALSE,,Ohio,State or jurisdiction,2430,2408,351,608,328,229,529,385,436.619,439.621
41,216.75,2019,A,,38,United States,,Oklahoma,,,,,,,,,,,,FALSE,,Oklahoma,State or jurisdiction,1234,1230,82,308,157,275,257,155,386.591,387.117
42,216.75,2019,A,,39,United States,,Oregon,,,,,,,,,,,,FALSE,,Oregon,State or jurisdiction,890,887,27,411,113,127,178,34,415.717,416.346
43,216.75,2019,A,,40,United States,,Pennsylvania,,,,,,,,,,,,FALSE,,Pennsylvania,State or jurisdiction,2102,2102,298,671,312,191,424,206,494.105,494.105
44,216.75,2019,A,,41,United States,,Rhode Island,,,,,,,,,,,,FALSE,,Rhode Island,State or jurisdiction,241,240,35,103,17,3,50,33,390.822,392.371
45,216.75,2019,A,,42,United States,,South Carolina,,,,,,,,,,,,FALSE,,South Carolina,State or jurisdiction,933,931,45,479,33,49,230,97,566.857,567.982
46,216.75,2019,A,,43,United States,,South Dakota,,,,,,,,,,,,FALSE,,South Dakota,State or jurisdiction,442,432,29,128,57,95,107,26,217.559,220.42
47,216.75,2019,A,,44,United States,,Tennessee,,,,,,,,,,,,FALSE,,Tennessee,State or jurisdiction,1351,1342,179,528,48,180,327,89,503.625,506.411
48,216.75,2019,A,,45,United States,,Texas,,,,,,,,,,,,FALSE,,Texas,State or jurisdiction,6156,6047,607,2933,430,149,1381,656,569.802,576.757
49,216.75,2019,A,,46,United States,,Utah,,,,,,,,,,,,FALSE,,Utah,State or jurisdiction,688,651,5,124,433,33,45,48,541.309,562.4
50,216.75,2019,A,,47,United States,,Vermont,,,,,,,,,,,,FALSE,,Vermont,State or jurisdiction,228,228,15,24,97,63,17,12,243.487,243.487
51,216.75,2019,A,,48,United States,,Virginia,,,,,,,,,,,,FALSE,,Virginia,State or jurisdiction,1490,1490,40,845,148,11,311,135,577.931,577.931
52,216.75,2019,A,,49,United States,,Washington,,,,,,,,,,,,FALSE,,Washington,State or jurisdiction,1583,1504,62,736,248,84,315,138,456.945,473.483
53,216.75,2019,A,,50,United States,,West Virginia,,,,,,,,,,,,FALSE,,West Virginia,State or jurisdiction,544,543,70,251,28,39,113,43,349.136,349.751
54,216.75,2019,A,,51,United States,,Wisconsin,,,,,,,,,,,,FALSE,,Wisconsin,State or jurisdiction,1577,1570,171,601,125,148,340,192,359.384,360.322
55,216.75,2019,A,,52,United States,,Wyoming,,,,,,,,,,,,FALSE,,Wyoming,State or jurisdiction,247,246,26,64,72,18,46,21,242.382,242.382
57,216.75,2019,A,,53,United States,,Jurisdiction,,Bureau of Indian Education,,,,,,,,,,FALSE,,Bureau of Indian Education,State or jurisdiction,111,111,7,6,28,62,4,4,211.766,211.766
58,216.75,2019,A,,54,United States,,Jurisdiction,,DoDEA,DoDEA = Department of Defense Education Activi...,,,,,,,,,FALSE,,DoDEA,State or jurisdiction,---,---,---,---,---,---,---,---,---,---
60,216.75,2019,A,,55,United States,,Jurisdiction,,Other jurisdictions,,American Samoa,,,,,,,,FALSE,,American Samoa,State or jurisdiction,22,22,0,0,0,22,0,0,348.545,348.545
61,216.75,2019,A,,56,United States,,Jurisdiction,,Other jurisdictions,,Guam,,,,,,,,FALSE,,Guam,State or jurisdiction,34,34,0,24,0,0,8,2,594.912,594.912
62,216.75,2019,A,,57,United States,,Jurisdiction,,Other jurisdictions,,Northern Marianas,,,,,,,,FALSE,,Northern Marianas,State or jurisdiction,---,---,---,---,---,---,---,---,---,---
63,216.75,2019,A,,58,United States,,Jurisdiction,,Other jurisdictions,,Puerto Rico,,,,,,,,FALSE,,Puerto Rico,State or jurisdiction,855,854,10,449,79,183,125,9,262.55,262.741
64,216.75,2019,A,,59,United States,,Jurisdiction,,Other jurisdictions,,U.S. Virgin Islands,,,,,,,,FALSE,,U.S. Virgin Islands,State or jurisdiction,19,19,1,1,14,1,2,0,325.895,325.895

In [7]:
tab.cell_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,is_standard_error,is_dollar,format_string,row_index,column_index,cell_note
0,216.75,2019,A,,FALSE,,,54,A,Not available.
1,216.75,2019,A,,FALSE,,,54,B,Not available.
2,216.75,2019,A,,FALSE,,,54,C,Not available.
3,216.75,2019,A,,FALSE,,,54,D,Not available.
4,216.75,2019,A,,FALSE,,,54,E,Not available.
5,216.75,2019,A,,FALSE,,,54,F,Not available.
6,216.75,2019,A,,FALSE,,,54,G,Not available.
7,216.75,2019,A,,FALSE,,,54,H,Not available.
8,216.75,2019,A,,FALSE,,,54,I,Not available.
9,216.75,2019,A,,FALSE,,,54,J,Not available.
10,216.75,2019,A,,FALSE,,,57,A,Not available.
11,216.75,2019,A,,FALSE,,,57,B,Not available.
12,216.75,2019,A,,FALSE,,,57,C,Not available.
13,216.75,2019,A,,FALSE,,,57,D,Not available.
14,216.75,2019,A,,FALSE,,,57,E,Not available.
15,216.75,2019,A,,FALSE,,,57,F,Not available.
16,216.75,2019,A,,FALSE,,,57,G,Not available.
17,216.75,2019,A,,FALSE,,,57,H,Not available.
18,216.75,2019,A,,FALSE,,,57,I,Not available.
19,216.75,2019,A,,FALSE,,,57,J,Not available.