In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
tabn = '203.65'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [4]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,digest_table_sub_title_note,has_SE,location_in,year_in,year,location,location_info,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,203.65,2019,A,,,FALSE,Title,Title,,United States,,Enrollment in public elementary and secondary ...,[In thousands],Year,Race categories exclude persons of Hispanic et...,"U.S. Department of Education, National Center ...",This table was prepared August 2019.

In [5]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,is_standard_error,is_dollar,format_string,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,203.65,2019,A,,A,FALSE,,,,,,All grades,,,,,,,,,,,,,
1,203.65,2019,A,,B,FALSE,,,,,,Elementary,Total,,,,,,,,,,,,
2,203.65,2019,A,,C,FALSE,,,,,,Elementary,Prekindergarten,,,,,,,,,,,,
3,203.65,2019,A,,D,FALSE,,,,,,Elementary,Kindergarten,,,,,,,,,,,,
4,203.65,2019,A,,E,FALSE,,,,,,Elementary,1st grade,,,,,,,,,,,,
5,203.65,2019,A,,F,FALSE,,,,,,Elementary,2nd grade,,,,,,,,,,,,
6,203.65,2019,A,,G,FALSE,,,,,,Elementary,3rd grade,,,,,,,,,,,,
7,203.65,2019,A,,H,FALSE,,,,,,Elementary,4th grade,,,,,,,,,,,,
8,203.65,2019,A,,I,FALSE,,,,,,Elementary,5th grade,,,,,,,,,,,,
9,203.65,2019,A,,J,FALSE,,,,,,Elementary,6th grade,,,,,,,,,,,,
10,203.65,2019,A,,K,FALSE,,,,,,Elementary,7th grade,,,,,,,,,,,,
11,203.65,2019,A,,L,FALSE,,,,,,Elementary,8th grade,,,,,,,,,,,,
12,203.65,2019,A,,M,FALSE,,,,,,Elementary,Ungraded,,,,,,,,,,,,
13,203.65,2019,A,,N,FALSE,,,,,,Secondary,Total,,,,,,,,,,,,
14,203.65,2019,A,,O,FALSE,,,,,,Secondary,9th grade,,,,,,,,,,,,
15,203.65,2019,A,,P,FALSE,,,,,,Secondary,10th grade,,,,,,,,,,,,
16,203.65,2019,A,,Q,FALSE,,,,,,Secondary,11th grade,,,,,,,,,,,,
17,203.65,2019,A,,R,FALSE,,,,,,Secondary,12th grade,,,,,,,,,,,,
18,203.65,2019,A,,S,FALSE,,,,,,Secondary,Ungraded,,,,,,,Includes students reported as being enrolled i...,,,,,

In [6]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S
6,203.65,2019,A,,1,Total,,,,,,,,,,,,,,FALSE,,,,46857.14899999999,33486.444,751.1749999999998,3397.1979999999994,3684.1229999999996,3655.721,3690.653,3686.3660000000004,3603.6639999999998,3564.116,3541.2729999999997,3496.977,415.178,13370.705,3934.876,3415.392,3033.9410000000003,2781.6209999999996,204.87499999999997
7,203.65,2019,A,,2,Total,,White,,,,,,,,,,,,FALSE,,,,29035.076,20327.377,354.2,2010.199,2158.881,2174.62,2218.589,2261.002,2239.59,2230.552,2242.87,2254.373,182.50099999999998,8707.699,2438.072,2214.471,2045.26,1919.84,90.056
8,203.65,2019,A,,3,Total,,Black,,,,,,,,,,,,FALSE,,,,8065.5149999999985,5951.997999999999,181.076,589.814,678.826,660.331,665.865,643.856,622.008,609.635,595.337,563.935,141.315,2113.517,695.195,536.727,432.06,379.801,69.734
9,203.65,2019,A,,4,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,7326.992,5512.431,180.03,626.526,661.87,635.895,620.089,593.639,555.716,538.078,522.129,499.325,79.134,1814.5610000000001,598.362,473.848,381.976,321.325,39.05
10,203.65,2019,A,,5,Total,,Asian/Pacific Islander,,,,,,,,,,,,FALSE,,,,1887.1530000000002,1303.3780000000002,27.238,131.968,141.6,142.251,143.396,144.663,143.216,143.667,138.408,137.966,9.005,583.775,156.16,150.58,141.181,131.41,4.444
11,203.65,2019,A,,6,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,542.413,391.26,8.631,38.691,42.946,42.624,42.714,43.206,43.134,42.184,42.529,41.378,3.223,151.15300000000002,47.087,39.766,33.464,29.245,1.591
14,203.65,2019,A,,7,Total,,,,,,,,,,,,,,FALSE,,,,47671.86999999999,33935.922,865.086,3379.151,3614.069,3593.3369999999995,3653.314,3694.898,3726.8349999999996,3768.8090000000007,3720.468,3615.9400000000005,304.01499999999993,13735.948000000002,4012.3489999999993,3527.859,3173.9390000000003,2862.861,158.94
15,203.65,2019,A,,8,Total,,White,,,,,,,,,,,,FALSE,,,,28731.977,19958.560999999998,404.358,1954.634,2073.014,2062.589,2113.736,2177.862,2228.332,2284.715,2282.342,2248.255,128.724,8773.416000000001,2408.109,2246.938,2107.926,1943.145,67.298
16,203.65,2019,A,,9,Total,,Black,,,,,,,,,,,,FALSE,,,,8181.025000000001,6006.293000000001,192.208,558.215,629.739,641.673,665.014,661.132,655.096,657.903,646.036,602.469,96.808,2174.732,722.711,555.277,453.414,392.718,50.612
17,203.65,2019,A,,10,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,8167.873999999999,6157.686999999999,225.188,683.064,716.974,695.999,679.576,658.178,644.788,626.516,592.832,566.444,68.128,2010.1870000000001,667.435,526.396,426.6,354.139,35.617
18,203.65,2019,A,,11,Total,,Asian/Pacific Islander,,,,,,,,,,,,FALSE,,,,2027.4600000000003,1408.6630000000002,32.722,143.519,152.093,151.815,152.21,153.272,153.495,154.061,152.899,154.809,7.768,618.797,164.932,157.451,150.623,141.73,4.061
19,203.65,2019,A,,12,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,563.534,404.71799999999996,10.61,39.719,42.249,41.261,42.778,44.454,45.124,45.614,46.359,43.963,2.587,158.816,49.162,41.797,35.376,31.129,1.352
22,203.65,2019,A,,13,Total,,,,,,,,,,,,,,FALSE,,,,48540.215,34200.74100000001,949.6490000000001,3503.28,3612.509,3543.7810000000004,3611.0410000000006,3619.0890000000004,3684.539,3771.934,3840.5139999999997,3809.431,254.97400000000002,14339.474000000002,4190.237,3675.2549999999997,3277.2180000000003,3046.491,150.273
23,203.65,2019,A,,14,Total,,White,,,,,,,,,,,,FALSE,,,,28442.491000000005,19558.481000000003,436.618,1974.552,2022.189,2005.958,2045.382,2068.842,2126.734,2202.648,2271.16,2297.251,107.147,8884.010000000002,2442.206,2255.08,2106.108,2017.469,63.147
24,203.65,2019,A,,15,Total,,Black,,,,,,,,,,,,FALSE,,,,8348.805,6014.8,198.11,587.914,618.56,599.759,632.507,640.587,653.594,676.616,681.349,652.373,73.431,2334.005,773.948,600.142,486.912,429.725,43.278
25,203.65,2019,A,,16,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,9010.910000000002,6729.295000000001,264.164,747.73,766.619,734.892,729.952,705.863,699.106,686.114,679.441,650.269,65.145,2281.6150000000002,740.049,601.932,486.844,414.395,38.395
26,203.65,2019,A,,17,Total,,Asian/Pacific Islander,,,,,,,,,,,,FALSE,,,,2145.22,1482.704,38.085,150.762,161.451,161.522,161.077,160.301,160.176,159.593,160.614,162.315,6.808,662.516,177.823,172.408,158.438,149.834,4.013
27,203.65,2019,A,,18,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,592.789,415.461,12.672,42.322,43.69,41.65,42.123,43.496,44.929,46.963,47.95,47.223,2.443,177.32799999999997,56.211,45.693,38.916,35.068,1.44
30,203.65,2019,A,,19,Total,,,,,,,,,,,,,,FALSE,,,,49113.298,34203.962,1036.466,3619.421,3690.8540000000003,3606.4049999999997,3586.1070000000004,3577.506,3632.829,3670.135,3777.151,3801.893,205.19500000000002,14909.336000000001,4287.1230000000005,3866.1580000000004,3454.423,3180.248,121.384
31,203.65,2019,A,,20,Total,,White,,,,,,,,,,,,FALSE,,,,28005.177000000003,19051.441000000003,464.793,1989.258,2023.498,1991.522,1991.174,2013.969,2050.558,2083.034,2158.194,2212.4,73.041,8953.736,2417.649,2304.485,2153.433,2034.962,43.207
32,203.65,2019,A,,21,Total,,Black,,,,,,,,,,,,FALSE,,,,8444.774000000001,5954.444,214.035,603.219,629.692,615.75,612.436,603.457,622.519,648.736,675.301,665.468,63.831,2490.33,803.232,651.391,534.236,463.711,37.76
33,203.65,2019,A,,22,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,9786.803,7216.376,300.799,815.072,824.833,788.381,770.24,746.98,746.867,726.088,729.222,707.904,59.99,2570.427,824.491,680.36,551.504,478.585,35.487
34,203.65,2019,A,,23,Total,,Asian/Pacific Islander,,,,,,,,,,,,FALSE,,,,2278.515,1569.432,43.023,168.743,168.146,167.975,170.198,170.587,169.857,167.668,167.884,168.762,6.589,709.083,185.526,181.35,173.125,165.184,3.898
35,203.65,2019,A,,24,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,598.029,412.269,13.816,43.129,44.685,42.777,42.059,42.513,43.028,44.609,46.55,47.359,1.744,185.76000000000002,56.225,48.572,42.125,37.806,1.032
38,203.65,2019,A,,25,Total,,,,,,,,,,,,,,FALSE,,,,49290.55900000001,34204.081,1081.1139999999998,3609.414,3750.072,3704.004,3658.857,3624.382,3600.0919999999996,3628.147,3700.418,3708.955,138.62599999999998,15086.478,4199.826,3862.846,3557.482,3374.5119999999997,91.812
39,203.65,2019,A,,26,Total,,White,,,,,,,,,,,,FALSE,,,,27454.384,18679.326999999997,490.927,1944.335,2008.632,2000.381,1996.33,1995.098,1996.703,2027.74,2075.648,2097.736,45.797,8775.056999999999,2291.211,2220.738,2142.708,2090.694,29.706000000000003
40,203.65,2019,A,,27,Total,,Black,,,,,,,,,,,,FALSE,,,,8391.782000000001,5820.771000000001,223.805,582.254,626.596,623.063,619.806,611.301,599.863,609.794,634.322,642.251,47.716,2571.0110000000004,797.45,668.647,564.346,508.644,31.924
41,203.65,2019,A,,28,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,10453.789999999999,7632.306999999999,310.213,862.645,885.806,849.806,821.397,796.951,781.462,768.903,768.515,747.66,38.949,2821.483,868.339,739.49,627.408,560.188,26.058
42,203.65,2019,A,,29,Total,,Asian/Pacific Islander,,,,,,,,,,,,FALSE,,,,2396.455,1660.12,41.792,176.744,183.949,186.877,177.32,177.438,179.316,178.213,177.329,176.067,5.075,736.3349999999999,190.483,186.466,180.706,175.284,3.396
43,203.65,2019,A,,30,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,594.148,411.556,14.377,43.436,45.089,43.877,44.004,43.594,42.748,43.497,44.604,45.241,1.089,182.592,52.343,47.505,42.314,39.702,0.728
46,203.65,2019,A,,31,Total,,,,,,,,,,,,,,FALSE,,,,49360.981999999975,34409.26,1222.8600000000001,3677.9709999999995,3728.773,3664.6969999999997,3707.038,3700.5299999999997,3652.134,3644.0570000000007,3641.342,3651.2760000000007,118.582,14951.721999999998,4080.016,3809.135,3540.9640000000004,3431.686,89.921
47,203.65,2019,A,,32,Total,,White,,,,,,,,,,,,FALSE,,,,26701.771999999997,18316.423,556.488,1932.333,1952.256,1924.05,1960.462,1978.087,1977.3,1984.353,1995.459,2021.055,34.58,8385.348999999998,2187.511,2116.211,2033.748,2021.657,26.222
48,203.65,2019,A,,33,Total,,Black,,,,,,,,,,,,FALSE,,,,8245.375,5713.173999999999,243.618,576.243,599.83,601.636,617.082,617.251,604.298,608.519,604.294,602.32,38.083,2532.201,740.973,655.861,572.517,533.972,28.878
49,203.65,2019,A,,34,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,10991.274999999998,7977.182999999999,350.626,903.109,906.55,876.467,867.457,842.504,818.918,801.796,791.554,778.73,39.472,3014.0919999999996,881.963,777.967,688.52,635.71,29.932
50,203.65,2019,A,,35,Total,,Asian,,,,,,,,,,,,FALSE,,,,2435.232,1696.7979999999998,46.729,183.908,190.738,185.727,184.969,187.541,177.28,176.475,178.814,179.349,5.268,738.434,190.89,187.188,180.116,176.245,3.995
51,203.65,2019,A,,36,Total,,Pacific Islander,,,,,,,,,,,,FALSE,,,,49.073,33.174,0.743,3.678,3.568,3.572,3.456,3.589,3.537,3.686,3.688,3.606,0.051,15.899,4.129,3.963,3.897,3.871,0.039
52,203.65,2019,A,,37,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,600.526,418.75,18.362,44.571,44.783,43.754,44.271,44.325,44.728,44.811,44.336,43.952,0.857,181.77599999999998,50.422,46.606,42.384,41.715,0.649
53,203.65,2019,A,,38,Total,,Two or more races,"For 2009, data on students of Two or more race...",,,,,,,,,,,FALSE,,,,337.729,253.758,6.294,34.129,31.048,29.491,29.341,27.233,26.073,24.417,23.197,22.264,0.271,83.97099999999999,24.128,21.339,19.782,18.516,0.206
56,203.65,2019,A,,39,Total,,,,,,,,,,,,,,FALSE,,,,49521.66899999998,34772.751000000004,1290.977,3746.4150000000004,3772.639,3713.225,3703.3140000000008,3671.865,3699.119,3723.5750000000003,3695.9950000000003,3679.1109999999994,76.516,14748.918000000001,3956.9900000000002,3751.3779999999997,3545.841,3451.8759999999997,42.833
57,203.65,2019,A,,40,Total,,White,,,,,,,,,,,,FALSE,,,,25602.203,17653.966,563.084,1845.304,1864.856,1866.006,1874.656,1871.976,1908.16,1933.324,1944.46,1950.763,31.377,7948.237000000001,2048.751,2008.242,1946.038,1927.642,17.564
58,203.65,2019,A,,41,Total,,Black,,,,,,,,,,,,FALSE,,,,7827.303,5469.883000000001,246.976,566.038,576.183,563.251,570.617,575.065,579.462,595.098,589.921,586.232,21.04,2357.4199999999996,670.146,602.101,547.197,526.198,11.778
59,203.65,2019,A,,42,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,11759.474999999999,8557.891,378.744,985.661,980.701,936.361,918.687,896.295,886.749,870.932,850.113,834.401,19.247,3201.584,907.918,822.677,751.195,709.02,10.774
60,203.65,2019,A,,43,Total,,Asian,,,,,,,,,,,,FALSE,,,,2334.143,1615.5069999999998,43.87,164.083,176.246,181.047,181.166,176.389,175.083,177.263,167.678,169.306,3.376,718.6360000000001,181.65,182.542,178.537,174.017,1.89
61,203.65,2019,A,,44,Total,,Pacific Islander,,,,,,,,,,,,FALSE,,,,178.635,128.2,3.208,14.447,15.331,14.488,14.041,13.644,13.161,13.46,13.288,12.919,0.213,50.434999999999995,13.958,12.842,12.114,11.401,0.12
62,203.65,2019,A,,45,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,547.4309999999999,384.118,18.579,40.696,40.438,40.004,39.635,39.921,40.181,40.786,41.853,41.444,0.581,163.31299999999996,44.412,41.294,38.528,38.753,0.326
63,203.65,2019,A,,46,Total,,Two or more races,,,,,,,,,,,,FALSE,,,,1272.479,963.186,36.516,130.186,118.884,112.068,104.512,98.575,96.323,92.712,88.682,84.046,0.682,309.293,90.155,81.68,72.232,64.845,0.381
66,203.65,2019,A,,47,Total,,,,,,,,,,,,,,FALSE,,,,50044.522000000004,35250.791999999994,1328.434,3833.526,3884.8199999999997,3791.1220000000003,3737.69,3707.733,3696.718,3684.4759999999997,3747.574,3753.3569999999995,85.342,14793.729999999998,3979.5210000000006,3760.5589999999993,3525.617,3476.1319999999996,51.901
67,203.65,2019,A,,48,Total,,White,,,,,,,,,,,,FALSE,,,,25160.247,17389.928,576.992,1827.987,1861.076,1832.333,1831.454,1851.348,1862.683,1863.84,1911.764,1933.677,36.773999999999994,7770.3189999999995,2017.736,1960.216,1883.725,1886.275,22.367000000000008
68,203.65,2019,A,,49,Total,,Black,,,,,,,,,,,,FALSE,,,,7804.8009999999995,5482.686999999999,247.956,586.523,604.924,581.319,571.157,557.975,557.459,573.177,587.9,592.494,21.803,2322.114,664.731,597.238,534.047,512.839,13.259
69,203.65,2019,A,,50,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,12452.324,9054.490000000002,392.218,1038.237,1039.083,1008.296,974.718,940.671,926.751,909.338,911.926,892.375,20.877,3397.8339999999994,953.857,872.131,792.251,766.899,12.696
70,203.65,2019,A,,51,Total,,Asian,,,,,,,,,,,,FALSE,,,,2416.9120000000003,1683.4470000000001,47.029,174.481,178.158,180.014,182.992,186.768,186.545,180.036,180.23,183.125,4.069,733.465,180.98,182.573,183.572,183.866,2.474
71,203.65,2019,A,,52,Total,,Pacific Islander,,,,,,,,,,,,FALSE,,,,176.197,125.537,3.037,13.6,13.894,13.441,14.46,14.039,13.613,13.263,12.987,13.056,0.147,50.66,14.135,12.996,11.961,11.479,0.089
72,203.65,2019,A,,53,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,523.4830000000001,367.18000000000006,16.985,39.123,39.676,38.574,38.213,38.079,37.984,38.692,39.425,39.807,0.622,156.303,43.409,40.18,36.204,36.132,0.378
73,203.65,2019,A,,54,Total,,Two or more races,,,,,,,,,,,,FALSE,,,,1510.558,1147.523,44.217,153.575,148.009,137.145,124.696,118.853,111.683,106.13,103.342,98.823,1.05,363.03499999999997,104.673,95.225,83.857,78.642,0.638
76,203.65,2019,A,,55,Total,,,,,,,,,,,,,,FALSE,,,,50438.04299999999,35387.986000000004,1401.6450000000002,3713.104,3768.136,3842.454,3868.9499999999994,3792.7349999999997,3732.882,3731.334,3731.547,3718.562,86.637,15050.057000000003,4019.4809999999998,3846.0350000000003,3597.832,3537.232,49.477
77,203.65,2019,A,,56,Total,,White,,,,,,,,,,,,FALSE,,,,24644.033000000003,16972.136000000002,600.446,1741.578,1767.562,1804.131,1828.735,1814.27,1816.146,1842.384,1859.547,1863.018,34.318999999999996,7671.897000000001,1978.099,1942.451,1871.83,1859.921,19.596000000000004
78,203.65,2019,A,,57,Total,,Black,,,,,,,,,,,,FALSE,,,,7783.937,5447.523,263.063,556.161,589.564,597.601,600.247,574.814,557.593,557.755,560.607,568.528,21.59,2336.4139999999998,656.077,601.733,541.594,524.68,12.33
79,203.65,2019,A,,58,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,13079.832,9423.503,413.478,1018.921,1021.18,1043.117,1046.677,1021.507,986.533,961.033,949.944,937.262,23.851,3656.329,1017.635,944.042,853.966,827.065,13.621
80,203.65,2019,A,,59,Total,,Asian,,,,,,,,,,,,FALSE,,,,2520.5869999999995,1753.6629999999998,53.794,182.941,180.426,188.649,189.208,189.573,190.971,193.511,192.245,187.636,4.709,766.924,195.145,197.847,184.73,186.512,2.69
81,203.65,2019,A,,60,Total,,Pacific Islander,,,,,,,,,,,,FALSE,,,,176.556,124.26900000000002,3.14,12.873,12.231,13.411,13.602,13.528,14.433,14.075,13.484,13.283,0.209,52.287,13.903,13.611,12.638,12.015,0.12
82,203.65,2019,A,,61,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,509.621,355.892,16.168,36.992,38.068,37.549,37.988,37.417,37.174,37.9,37.824,38.225,0.587,153.729,41.474,39.449,36.328,36.142,0.336
83,203.65,2019,A,,62,Total,,Two or more races,,,,,,,,,,,,FALSE,,,,1723.4769999999999,1311.0,51.556,163.638,159.105,157.996,152.493,141.626,130.032,124.676,117.896,110.61,1.372,412.477,117.148,106.902,96.746,90.897,0.784
86,203.65,2019,A,,63,Total,,,,,,,,,,,,,,FALSE,,,,50685.56700000001,35496.056000000004,1471.2159999999997,3684.2379999999994,3667.1659999999993,3684.091,3787.97,3859.475000000001,3877.2670000000003,3827.0229999999997,3776.565,3772.2760000000003,88.76899999999998,15189.511000000002,3995.5740000000005,3833.718,3676.7529999999997,3631.4500000000007,52.016
87,203.65,2019,A,,64,Total,,White,,,,,,,,,,,,FALSE,,,,24124.478000000003,16623.155000000002,627.304,1711.364,1703.462,1708.379,1751.321,1795.585,1820.564,1811.905,1816.026,1842.832,34.413,7501.323,1919.715,1872.577,1839.926,1848.652,20.453
88,203.65,2019,A,,65,Total,,Black,,,,,,,,,,,,FALSE,,,,7709.399000000001,5409.093000000001,263.133,538.559,557.157,562.709,591.793,591.793,589.357,576.316,561.318,556.081,20.877,2300.306,621.834,585.139,545.63,535.581,12.122
89,203.65,2019,A,,66,Total,,Hispanic,,,,,,,,,,,,FALSE,,,,13570.93,9678.458,439.053,1008.473,996.381,1005.691,1039.104,1059.294,1060.265,1042.614,1012.12,989.948,25.515,3892.472,1058.082,1000.294,929.996,889.316,14.784
90,203.65,2019,A,,67,Total,,Asian,,,,,,,,,,,,FALSE,,,,2639.5969999999998,1826.7179999999998,62.345,198.756,190.115,191.44,191.1,197.629,196.79,195.667,196.84,200.632,5.404,812.879,205.715,201.733,200.163,202.148,3.12
91,203.65,2019,A,,68,Total,,Pacific Islander,,,,,,,,,,,,FALSE,,,,185.12099999999998,129.432,3.494,13.475,13.517,13.511,12.977,14.034,14.357,14.395,14.996,14.344,0.332,55.689,15.089,14.266,13.236,12.905,0.193
92,203.65,2019,A,,69,Total,,American Indian/Alaska Native,,,,,,,,,,,,FALSE,,,,497.50800000000004,347.25500000000005,16.722,35.057,34.852,35.666,36.991,37.195,37.669,37.557,37.377,37.675,0.494,150.25300000000001,40.451,37.986,35.673,35.838,0.305
93,203.65,2019,A,,70,Total,,Two or more races,,,,,,,,,,,,FALSE,,,,1958.5339999999997,1481.9449999999997,59.165,178.554,171.682,166.695,164.684,163.945,158.265,148.569,137.888,130.764,1.734,476.589,134.688,121.723,112.129,107.01,1.039

In [7]:
tab.cell_info

Empty DataFrame
Columns: [digest_table_id, digest_table_year, digest_table_sub_id, digest_table_sub_title, is_standard_error, is_dollar, format_string, row_index, column_index, cell_note]
Index: []