In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
tabn = '236.55'
tab = Table('100tables/tabn' + tabn + '.xls', '2019')

In [4]:
tab.table_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,digest_table_sub_title_note,has_SE,location_in,year_in,year,location,location_info,table_title,headnote,stub_head,general_note,source_note,last_prepared
0,236.55,2019,A,,,FALSE,Title,Row,,United States,,Total and current expenditures per pupil in pu...,,School year,"Beginning in 1980-81, state administration exp...","U.S. Department of Education, National Center ...",This table was prepared August 2019.

In [5]:
tab.col_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,column_index,is_standard_error,is_dollar,format_string,year,location,location_type,column_level_1,column_level_2,column_level_3,column_level_4,column_level_5,column_level_6,column_level_7,column_ref_note_1,column_ref_note_2,column_ref_note_3,column_ref_note_4,column_ref_note_5,column_ref_note_6,column_ref_note_7
0,236.55,2019,A,,A,FALSE,,,,,,Expenditure per pupil in average daily attendance,Unadjusted dollars,Total expenditure,,,,,,"Unadjusted (or ""current"") dollars have not bee...","Excludes ""Other current expenditures,"" such as...",,,,
1,236.55,2019,A,,B,FALSE,,,,,,Expenditure per pupil in average daily attendance,Unadjusted dollars,Current expenditure,,,,,,"Unadjusted (or ""current"") dollars have not bee...",,,,,
2,236.55,2019,A,,C,FALSE,,,,,,Expenditure per pupil in average daily attendance,Constant 2018-19 dollars,Total expenditure,,,,,,Constant dollars based on the Consumer Price I...,"Excludes ""Other current expenditures,"" such as...",,,,
3,236.55,2019,A,,D,FALSE,,,,,,Expenditure per pupil in average daily attendance,Constant 2018-19 dollars,Current expenditure,,,,,,Constant dollars based on the Consumer Price I...,,,,,
4,236.55,2019,A,,E,FALSE,,,,,,Expenditure per pupil in fall enrollment,Unadjusted dollars,Total expenditure,,,,,Data for 1919-20 to 1953-54 are based on schoo...,"Unadjusted (or ""current"") dollars have not bee...","Excludes ""Other current expenditures,"" such as...",,,,
5,236.55,2019,A,,F,FALSE,,,,,,Expenditure per pupil in fall enrollment,Unadjusted dollars,Current expenditure,,,,,Data for 1919-20 to 1953-54 are based on schoo...,"Unadjusted (or ""current"") dollars have not bee...",,,,,
6,236.55,2019,A,,G,FALSE,,,,,,Expenditure per pupil in fall enrollment,Constant 2018-19 dollars,Total expenditure,,,,,Data for 1919-20 to 1953-54 are based on schoo...,Constant dollars based on the Consumer Price I...,"Excludes ""Other current expenditures,"" such as...",,,,
7,236.55,2019,A,,H,FALSE,,,,,,Expenditure per pupil in fall enrollment,Constant 2018-19 dollars,Current expenditure,,,,,Data for 1919-20 to 1953-54 are based on schoo...,Constant dollars based on the Consumer Price I...,,,,,
8,236.55,2019,A,,I,FALSE,,,,,,Expenditure per pupil in fall enrollment,Constant 2018-19 dollars,Annual percent change in current expenditure,,,,,Data for 1919-20 to 1953-54 are based on schoo...,Constant dollars based on the Consumer Price I...,,,,,

In [6]:
tab.row_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,row_index,row_level_1,row_ref_note_1,row_level_2,row_ref_note_2,row_level_3,row_ref_note_3,row_level_4,row_ref_note_4,row_level_5,row_ref_note_5,row_level_6,row_ref_note_6,row_level_7,row_ref_note_7,is_total,year,location,location_type,A,B,C,D,E,F,G,H,I
5,236.55,2019,A,,1,1919-20,,,,,,,,,,,,,,FALSE,1919-20,,,63.95490783766103,53.32000828481176,849.9177037584602,708.587042621351,47.86629318061706,39.90672858808815,636.1108375101544,530.3335783423187,---
6,236.55,2019,A,,2,1929-30,,,,,,,,,,,,,,FALSE,1929-30,,,108.48706172231537,86.69464336653392,1605.2054184896517,1282.7585988289602,89.84203023481372,71.79494629939269,1329.3282300350995,1062.2984436148033,---
7,236.55,2019,A,,3,1931-32,,,,,,,,,,,,,,FALSE,1931-32,,,96.87247516295797,81.08326212632052,1701.7894180184533,1424.4153174869216,82.01301778341227,68.6457428440497,1440.7486292549947,1205.921481488991,---
8,236.55,2019,A,,4,1933-34,,,,,,,,,,,,,,FALSE,1933-34,,,76.22356378675218,67.48229478867175,1457.8605613308528,1290.6740550171664,64.75867366179857,57.33219084842121,1238.581767178402,1096.5420111613007,---
9,236.55,2019,A,,5,1935-36,,,,,,,,,,,,,,FALSE,1935-36,,,87.94581662854837,74.29924830709898,1620.860215825876,1369.3510420784705,74.37692858728708,62.83584708487829,1370.7827062614629,1158.0781050424214,---
11,236.55,2019,A,,6,1937-38,,,,,,,,,,,,,,FALSE,1937-38,,,99.69618193396778,83.8672923374981,1762.6424157802549,1482.7854377475371,85.58368280894155,71.99545264643366,1513.1314609183253,1272.8896545100845,---
12,236.55,2019,A,,7,1939-40,,,,,,,,,,,,,,FALSE,1939-40,,,105.73749304230788,88.09481561032769,1916.2735876808035,1596.536512343218,91.63811269385914,76.34796710580068,1660.7514508585557,1383.6491544151645,---
13,236.55,2019,A,,8,1941-42,,,,,,,,,,,,,,FALSE,1941-42,,,110.02777609243498,98.31488692881938,1787.2315800012072,1596.9737546618924,94.20851715541835,84.17965027381405,1530.2721089609092,1367.368629139837,---
14,236.55,2019,A,,9,1943-44,,,,,,,,,,,,,,FALSE,1943-44,,,124.67456134265163,116.98908835382339,1812.113446320269,1700.4070260657757,105.04301209939597,98.56771173771037,1526.7738070811945,1432.656942116868,---
15,236.55,2019,A,,10,1945-46,,,,,,,,,,,,,,FALSE,1945-46,,,145.8718225603305,136.40187213461635,2025.2529742467812,1893.7742216747074,124.26682994605007,116.19946848792449,1725.2939089341194,1613.2883995723967,---
17,236.55,2019,A,,11,1947-48,,,,,,,,,,,,,,FALSE,1947-48,,,204.8541367766619,181.4778574844572,2226.7380906932017,1972.6409446083046,178.8926173207311,158.47885437894547,1944.5397168921425,1722.6447420964273,---
18,236.55,2019,A,,12,1949-50,,,,,,,,,,,,,,FALSE,1949-50,,,260.36748339615866,210.342577634177,2784.3918331621126,2249.4212706267253,231.05134566824896,186.65900587808093,2470.8825830640576,1996.1471562187983,---
19,236.55,2019,A,,13,1951-52,,,,,,,,,,,,,,FALSE,1951-52,,,314.47757664359114,246.04041793868515,3030.365897400184,2370.8923855912535,275.3415470677188,215.42123937568914,2653.243653416543,2075.840142076705,---
20,236.55,2019,A,,14,1953-54,,,,,,,,,,,,,,FALSE,1953-54,,,350.9604692676858,264.8166105655422,3305.334528130606,2494.03440892138,312.1087796623477,235.50113586977855,2939.430552116744,2217.9422013783683,---
21,236.55,2019,A,,15,1955-56,,,,,,,,,,,,,,FALSE,1955-56,,,387.03075626740605,294.21999999999997,3646.263645364483,2771.8822661161325,353.7887632547694,268.94950398437976,3333.086801770968,2533.805861515303,---
23,236.55,2019,A,,16,1957-58,,,,,,,,,,,,,,FALSE,1957-58,,,447.4457804577948,341.14,3968.1944787794932,3025.416538973317,408.07074631610783,311.1198283194178,3618.995089921843,2759.181198921574,---
24,236.55,2019,A,,17,1959-60,,,,,,,,,,,,,,FALSE,1959-60,,,471.0229899843374,375.14,4060.002403680808,3233.5349528639013,440.0130201675312,350.4425216933392,3792.710669155304,3020.6540034791765,---
25,236.55,2019,A,,18,1961-62,,,,,,,,,,,,,,FALSE,1961-62,,,517.140637248146,419.00000000000006,4357.414828483713,3530.4841306806843,485.2447707635854,393.1571884040161,4088.6610087747604,3312.733208886431,---
26,236.55,2019,A,,19,1963-64,,,,,,,,,,,,,,FALSE,1963-64,,,558.6801923953707,460.3240021710433,4587.763924764631,3780.0836321203483,520.0088208175873,428.46076310075426,4270.202776435663,3518.429432235323,---
27,236.55,2019,A,,20,1965-66,,,,,,,,,,,,,,FALSE,1965-66,,,653.8130728636355,537.6976238514825,5189.60540735951,4267.945399198235,607.0058626970075,499.20324873065636,4818.075743811762,3962.3984079076054,---
29,236.55,2019,A,,21,1967-68,,,,,,,,,,,,,,FALSE,1967-68,,,786.4894319371538,658.3027589055688,5857.2278713202495,4902.582425973171,731.5949628366109,612.3553132182991,5448.411933889166,4560.39771430758,---
30,236.55,2019,A,,22,1969-70,,,,,,,,,,,,,,FALSE,1969-70,,,955.0070805870582,815.9838362683637,6402.984335833834,5470.882706658264,879.1959672523666,751.2087740221334,5894.697663377165,5036.58884921344,---
31,236.55,2019,A,,23,1970-71,,,,,,,,,,,,,,FALSE,1970-71,,,1049.4594253985038,911.1211914779961,6690.861919492215,5808.88211260539,970.2010678529375,842.3105567704334,6185.547742051045,5370.177724156932,6.623309643303283
32,236.55,2019,A,,24,1971-72,,,,,,,,,,,,,,FALSE,1971-72,,,1127.8141059914603,989.6699202390707,6941.414896628073,6091.1718434777395,1034.3735920608494,907.6747887031776,6366.3118083612935,5586.512232935027,4.02844225815744
33,236.55,2019,A,,25,1972-73,,,,,,,,,,,,,,FALSE,1972-73,,,1210.5887526968397,1076.8984565779178,7162.291913147617,6371.330552713888,1116.67251449097,993.3537749127374,6606.64862642728,5877.049239969146,5.200686849323825
35,236.55,2019,A,,26,1973-74,,,,,,,,,,,,,,FALSE,1973-74,,,1363.8948392702032,1207.2149430569302,7408.706019351976,6557.617462694748,1243.6442490092427,1100.7783577025016,6755.502233953306,5979.451648227286,1.7424119498899686
36,236.55,2019,A,,27,1974-75,,,,,,,,,,,,,,FALSE,1974-75,,,1544.7447741065407,1364.5282246411714,7553.954654163101,6672.677911616083,1423.099292552348,1257.0744266008003,6959.096223859825,6147.2182166421735,2.8057182879742024
37,236.55,2019,A,,28,1975-76,,,,,,,,,,,,,,FALSE,1975-76,,,1697.2958382077707,1503.623116415619,7751.284257477833,6866.8112706616,1562.8731774575733,1384.5389735548683,7137.3970195161155,6322.972641535836,2.8590887568924814
38,236.55,2019,A,,29,1976-77,,,,,,,,,,,,,,FALSE,1976-77,,,1816.2565634796238,1637.5508179858934,7837.519036995798,7066.367146623923,1673.6576674947687,1508.9825620141073,7222.175596862691,6511.568791593215,2.9827133652055293
39,236.55,2019,A,,30,1977-78,,,,,,,,,,,,,,FALSE,1977-78,,,2002.405314026416,1822.823611718583,8097.092412511653,7370.920928148773,1841.680176544832,1676.5127856605766,7447.170899576206,6779.286321885953,4.111413683264404
41,236.55,2019,A,,31,1978-79,,,,,,,,,,,,,,FALSE,1978-79,,,2209.9119975344356,2020.4619033496324,8170.802799876664,7470.340807847514,2029.432402276493,1855.454361439606,7503.507819850552,6860.251316979359,1.1942996836115687
42,236.55,2019,A,,32,1979-80,,,,,,,,,,,,,,FALSE,1979-80,,,2490.6421600760596,2271.7841727073405,8125.410052402245,7411.413108513683,2289.6121439652698,2088.419088730104,7469.574645805212,6813.207344357374,-0.6857470732238362
43,236.55,2019,A,,33,1980-81,,,,,,,,,,,,,,FALSE,1980-81,,,2742.330443363927,2501.637317503535,8017.830265280174,7314.10886152364,2529.4152787937205,2307.409622427566,7395.324084612156,6746.239772040229,-0.9829081801334985
44,236.55,2019,A,,34,1981-82,,,,,,,,,,,,,,FALSE,1981-82,,,2973.380421522758,2725.690053649782,8002.105162135268,7335.508867554012,2754.376581834429,2524.9298067507734,7412.711439282974,6795.213183747979,0.7259364232905077
45,236.55,2019,A,,35,1982-83,,,,,,,,,,,,,,FALSE,1982-83,,,3203.3955084672757,2955.2382108156958,8266.09855974009,7625.7490695554725,2966.191472847253,2736.409649693256,7654.013061080775,7061.079971049532,3.9125599169930823
47,236.55,2019,A,,36,1983-84,,,,,,,,,,,,,,FALSE,1983-84,,,3471.2503469875323,3173.346858444872,8637.55865793736,7896.28142366226,3215.734473498985,2939.7594149113474,8001.755093032638,7315.042664254022,3.5966551043995922
48,236.55,2019,A,,37,1984-85,,,,,,,,,,,,,,FALSE,1984-85,,,3721.899477646312,3470.4039452964034,8912.402137760608,8310.174878906744,3455.7266159174856,3222.216869040731,8275.028776085072,7715.869997146634,5.479494123134925
49,236.55,2019,A,,38,1985-86,,,,,,,,,,,,,,FALSE,1985-86,,,4019.83369266297,3755.5671247867413,9356.031131839374,8740.959358928187,3724.2388829921474,3479.404916513412,8668.043903228863,8098.200872984174,4.955123349394527
50,236.55,2019,A,,39,1986-87,,,,,,,,,,,,,,FALSE,1986-87,,,4307.9663888761315,3970.4169342841888,9808.869952063507,9040.29879723003,3994.858573801356,3681.842591076759,9095.950313931315,8383.239770183567,3.5197805249594536
51,236.55,2019,A,,40,1987-88,,,,,,,,,,,,,,FALSE,1987-88,,,4654.020043396203,4240.079701097203,10175.18989961214,9270.182712120702,4309.983377662982,3926.6425286728017,9423.014710501788,8584.907891368443,2.4056107986096587
53,236.55,2019,A,,41,1988-89,,,,,,,,,,,,,,FALSE,1988-89,,,5107.769443452828,4644.697098980594,10674.256975744363,9706.524728237979,4736.574378960845,4307.154721962819,9898.530594516596,9001.125999423059,4.848253625098248
54,236.55,2019,A,,42,1989-90,,,,,,,,,,,,,,FALSE,1989-90,,,5546.997610910424,4979.705412682949,11064.201542981384,9932.664150103446,5171.647877535556,4642.742747463925,10315.518130716087,9260.548691984197,2.882113777518129
55,236.55,2019,A,,43,1990-91,,,,,,,,,,,,,,FALSE,1990-91,,,5881.820174843101,5257.76549695282,11123.88144927203,9943.64981206454,5483.653691076401,4901.84404098151,10370.856597978882,9270.52007266669,0.10767591655907012
56,236.55,2019,A,,44,1991-92,,,,,,,,,,,,,,FALSE,1991-92,,,6072.048931511462,5421.097162215655,11127.110505803174,9934.232722273924,5626.381601649472,5023.207434307011,10310.41919054294,9205.094498669165,-0.7057379034260081
57,236.55,2019,A,,45,1992-93,,,,,,,,,,,,,,FALSE,1992-93,,,6279.368149454512,5583.6611574562885,11158.484563943486,9922.207991767335,5802.388632201079,5159.527400683069,10310.888364148766,9168.519106937025,-0.3973385796031516
59,236.55,2019,A,,46,1993-94,,,,,,,,,,,,,,FALSE,1993-94,,,6489.088439626446,5767.46120947902,11239.995697677497,9990.03785881486,5993.650021295338,5327.118642723251,10381.828060987626,9227.303832011545,0.6411583418094484
60,236.55,2019,A,,47,1994-95,,,,,,,,,,,,,,FALSE,1994-95,,,6722.874424995428,5989.022894954108,11320.468059343533,10084.75513642384,6206.106975480899,5528.664439498997,10450.297201386205,9309.569871702517,0.8915501341309836
61,236.55,2019,A,,48,1995-96,,,,,,,,,,,,,,FALSE,1995-96,,,6959.33842406928,6146.9125843015745,11408.27005816944,10076.480623953988,6441.136340687334,5689.20486649106,10558.794296007765,9326.171767808788,0.17833150548377397
62,236.55,2019,A,,49,1996-97,,,,,,,,,,,,,,FALSE,1996-97,,,7297.182376136261,6392.84161813529,11630.268998661355,10188.928253718434,6761.378609229882,5923.440081532007,10776.303506446711,9440.794815676041,1.229047145184463
63,236.55,2019,A,,50,1997-98,,,,,,,,,,,,,,FALSE,1997-98,,,7700.509750694563,6675.55719564435,12058.047405985524,10453.098266538396,7139.397642182608,6189.13018044548,11179.415130518388,9691.41362503905,2.654636757350833
65,236.55,2019,A,,51,1998-99,,,,,,,,,,,,,,FALSE,1998-99,,,8115.457023415651,7013.182036767558,12491.555769386752,10794.900925526892,7530.953714321139,6508.068388091303,11591.870679332245,10017.414790844332,3.3638143868198496
66,236.55,2019,A,,52,1999-2000,,,,,,,,,,,,,,FALSE,1999-2000,,,8588.981504461211,7393.579420132881,12849.47999711671,11061.107864389423,8029.834665890579,6912.2538338173335,12012.972651754219,10341.024407433597,3.2304703693116124
67,236.55,2019,A,,53,2000-01,,,,,,,,,,,,,,FALSE,2000-01,,,9179.73314108176,7903.6526610555875,13278.348829046987,11432.517203300129,8571.502982964896,7379.972959929971,12398.552860722095,10675.022226118519,3.229832998409996
68,236.55,2019,A,,54,2001-02,,,,,,,,,,,,,,FALSE,2001-02,,,9611.208357830074,8258.746234423583,13660.610568212416,11738.32799059437,8992.809122612569,7727.366394857183,12781.666858589835,10983.066759970643,2.885657072436188
69,236.55,2019,A,,55,2002-03,,,,,,,,,,,,,,FALSE,2002-03,,,9950.070698081807,8609.869985112411,13838.131798502991,11974.238097115172,9296.330970602423,8044.184149454438,12928.938609300712,11187.50648606336,1.8614083894839466
71,236.55,2019,A,,56,2003-04,,,,,,,,,,,,,,FALSE,2003-04,,,10307.669143824725,8899.809437557658,14028.559791491309,12112.487031314366,9625.06323571084,8310.436377712786,13099.54493251732,11310.36046960945,1.0981355291202182
72,236.55,2019,A,,57,2004-05,,,,,,,,,,,,,,FALSE,2004-05,,,10778.622887182859,9316.017497643537,14240.9712527963,12308.542451396946,10078.38752714008,8710.800584972401,13315.803748845614,11508.915565358962,1.7555151870094963
73,236.55,2019,A,,58,2005-06,,,,,,,,,,,,,,FALSE,2005-06,,,11337.709339102948,9778.261071801582,14430.122662699634,12445.32757665154,10603.224467251206,9144.801118344767,13495.303602013038,11639.088454012937,1.1310612882223787
74,236.55,2019,A,,59,2006-07,,,,,,,,,,,,,,FALSE,2006-07,,,12015.142049506225,10335.718232589345,14906.832616143698,12823.22098448813,11251.820694078922,9679.090585732769,13959.802307987637,12008.562415950812,3.1744235246402535
75,236.55,2019,A,,60,2007-08,,,,,,,,,,,,,,FALSE,2007-08,,,12759.185721819202,10982.007475948903,15264.350121367326,13138.23709468322,11964.709183758789,10298.190540395944,14313.884448669454,12320.158155260697,2.594779695661129
77,236.55,2019,A,,61,2008-09,,,,,,,,,,,,,,FALSE,2008-09,,,13032.826917886208,11238.548086491293,15377.00904620002,13259.997748835249,12222.306794149568,10539.615349712458,14420.702685856912,12435.349720909422,0.9349844717662059
78,236.55,2019,A,,62,2009-10,,,,,,,,,,,,,,FALSE,2009-10,,,13035.261888347983,11426.923237718875,15232.494557584685,13353.053242764592,12133.101324488289,10636.074568960108,14178.26519136503,12428.898580900126,-0.05187743130737045
79,236.55,2019,A,,63,2010-11,,,,,,,,,,,,,,FALSE,2010-11,,,12925.646978060133,11433.342995342653,14807.079379788653,13097.558489393059,12054.244712398102,10662.546685715455,13808.83747040596,12214.566546191236,-1.7244652316840117
80,236.55,2019,A,,64,2011-12,,,,,,,,,,,,,,FALSE,2011-12,,,12795.745505503026,11362.111263841869,14240.998715477952,12645.438426694362,11991.280766108466,10647.778685649568,13345.671333776103,11850.423448935884,-2.9812199710754315
81,236.55,2019,A,,65,2012-13,,,,,,,,,,,,,,FALSE,2012-13,,,12858.619663797681,11509.186201718552,14076.718096280607,12599.45265628503,12033.478102345902,10770.638198758137,13173.410785404672,11790.941921068657,-0.5019358854435529
83,236.55,2019,A,,66,2013-14,,,,,,,,,,,,,,FALSE,2013-14,,,13174.346935202428,11819.444077730474,14200.524755006463,12740.085640810337,12334.941317716844,11066.366312039218,13295.736053963168,11928.349051001203,1.1653617739140918
84,236.55,2019,A,,67,2014-15,,,,,,,,,,,,,,FALSE,2014-15,,,13667.66719490811,12224.369055597235,14625.76733320089,13081.294346189114,12795.938948765157,11444.694832843994,13692.93114952384,12246.965150499342,2.671082964925438
85,236.55,2019,A,,68,2015-16,,,,,,,,,,,,,,FALSE,2015-16,,,14170.811217349456,12618.54039372199,15062.60892084148,13412.650566523194,13298.880544017917,11842.121016369141,14135.805893333822,12587.36955330138,2.7795000526163727
86,236.55,2019,A,,69,2016-17,,,,,,,,,,,,,,FALSE,2016-17,,,14777.763896715986,13094.077778958299,15424.035286963703,13666.717043556353,13833.77058238293,12257.637166759823,14438.7586041926,12793.696632067318,1.6391596186339314

In [7]:
tab.cell_info

,digest_table_id,digest_table_year,digest_table_sub_id,digest_table_sub_title,is_standard_error,is_dollar,format_string,row_index,column_index,cell_note
0,236.55,2019,A,,FALSE,,,1,I,Not available.
1,236.55,2019,A,,FALSE,,,2,I,Not available.
2,236.55,2019,A,,FALSE,,,3,I,Not available.
3,236.55,2019,A,,FALSE,,,4,I,Not available.
4,236.55,2019,A,,FALSE,,,5,I,Not available.
5,236.55,2019,A,,FALSE,,,6,I,Not available.
6,236.55,2019,A,,FALSE,,,7,I,Not available.
7,236.55,2019,A,,FALSE,,,8,I,Not available.
8,236.55,2019,A,,FALSE,,,9,I,Not available.
9,236.55,2019,A,,FALSE,,,10,I,Not available.
10,236.55,2019,A,,FALSE,,,11,I,Not available.
11,236.55,2019,A,,FALSE,,,12,I,Not available.
12,236.55,2019,A,,FALSE,,,13,I,Not available.
13,236.55,2019,A,,FALSE,,,14,I,Not available.
14,236.55,2019,A,,FALSE,,,15,I,Not available.
15,236.55,2019,A,,FALSE,,,16,I,Not available.
16,236.55,2019,A,,FALSE,,,17,I,Not available.
17,236.55,2019,A,,FALSE,,,18,I,Not available.
18,236.55,2019,A,,FALSE,,,19,I,Not available.
19,236.55,2019,A,,FALSE,,,20,I,Not available.
20,236.55,2019,A,,FALSE,,,21,I,Not available.
21,236.55,2019,A,,FALSE,,,22,I,Not available.
22,236.55,2019,A,,FALSE,,,33,A,Estimated.
23,236.55,2019,A,,FALSE,,,33,C,Estimated.
24,236.55,2019,A,,FALSE,,,33,E,Estimated.
25,236.55,2019,A,,FALSE,,,33,G,Estimated.
26,236.55,2019,A,,FALSE,,,34,A,Estimated.
27,236.55,2019,A,,FALSE,,,34,C,Estimated.
28,236.55,2019,A,,FALSE,,,34,E,Estimated.
29,236.55,2019,A,,FALSE,,,34,G,Estimated.
30,236.55,2019,A,,FALSE,,,35,A,Estimated.
31,236.55,2019,A,,FALSE,,,35,C,Estimated.
32,236.55,2019,A,,FALSE,,,35,E,Estimated.
33,236.55,2019,A,,FALSE,,,35,G,Estimated.
34,236.55,2019,A,,FALSE,,,36,A,Estimated.
35,236.55,2019,A,,FALSE,,,36,C,Estimated.
36,236.55,2019,A,,FALSE,,,36,E,Estimated.
37,236.55,2019,A,,FALSE,,,36,G,Estimated.
38,236.55,2019,A,,FALSE,,,37,A,Estimated.
39,236.55,2019,A,,FALSE,,,37,C,Estimated.
40,236.55,2019,A,,FALSE,,,37,E,Estimated.
41,236.55,2019,A,,FALSE,,,37,G,Estimated.
42,236.55,2019,A,,FALSE,,,38,A,Estimated.
43,236.55,2019,A,,FALSE,,,38,C,Estimated.
44,236.55,2019,A,,FALSE,,,38,E,Estimated.
45,236.55,2019,A,,FALSE,,,38,G,Estimated.
46,236.55,2019,A,,FALSE,,,39,A,Estimated.
47,236.55,2019,A,,FALSE,,,39,C,Estimated.
48,236.55,2019,A,,FALSE,,,39,E,Estimated.
49,236.55,2019,A,,FALSE,,,39,G,Estimated.
50,236.55,2019,A,,FALSE,,,40,A,Estimated.
51,236.55,2019,A,,FALSE,,,40,C,Estimated.
52,236.55,2019,A,,FALSE,,,40,E,Estimated.
53,236.55,2019,A,,FALSE,,,40,G,Estimated.